Repository yiisoft/yii2, pull requests merged in 2018-06, with the labels that each got.

#16377 Fix Event off method undefined index error
  framework/CHANGELOG.md
  framework/base/Event.php
  tests/framework/base/EventTest.php
Labels: type:bug

#16285 Xml element attributes feature
  framework/CHANGELOG.md
  framework/web/XmlResponseFormatter.php
  tests/framework/helpers/JsonTest.php
  tests/framework/web/JsonResponseFormatterTest.php
  tests/framework/web/Post.php
  tests/framework/web/XmlResponseFormatterTest.php
Labels: type:enhancement

#16362 Fix define command::executeResetSequence() to work with Oracle
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/QueryBuilder.php
  framework/db/oci/QueryBuilder.php
  framework/test/ActiveFixture.php
  tests/framework/db/oci/QueryBuilderTest.php
Labels: Oracle, type:bug

#16446 Fixed drop existing views when console `migrate/fresh` command runs
  framework/CHANGELOG.md
  framework/console/controllers/MigrateController.php
  tests/framework/console/controllers/MigrateControllerTest.php
Labels: type:bug
