Repository yiisoft/yii2, pull requests merged in 2018-02, with the labels that each got.

#15631 Fixes #15627: Corrected session freezing/unfreezing not to attempt opening or closing connection if it isn't necessary
  framework/web/DbSession.php
  framework/web/Session.php
  tests/framework/web/session/AbstractDbSessionTest.php
Labels: type:bug

#15398 Copy query cache from `yii\db\Command` to `yii\db\Query::createCommand()` and `yii\db\ActiveQuery::createCommand()`.
  framework/db/ActiveQuery.php
  framework/db/CacheableQueryTrait.php
  framework/db/Command.php
  framework/db/Query.php
Labels: feature:db, status:under discussion

#15638 #14811 fixed freeze/unfreeze in HttpCache
  framework/CHANGELOG.md
  framework/filters/HttpCache.php
  framework/web/Session.php
  tests/framework/web/session/CacheSessionTest.php
Labels: severity:important, type:bug

#15639 Added test for #15630
  tests/framework/db/QueryTest.php
Labels: type:test

#15641 Added BetweenConditionBuilder
  docs/guide/db-query-builder.md
  framework/CHANGELOG.md
  framework/db/QueryBuilder.php
  framework/db/conditions/BetweenColumnsCondition.php
  framework/db/conditions/BetweenColumnsConditionBuilder.php
  tests/framework/db/QueryBuilderTest.php
Labels: feature:db, type:enhancement

#15642 15630 fixed like escaping
  framework/db/conditions/InCondition.php
  framework/db/conditions/LikeCondition.php
  framework/db/conditions/LikeConditionBuilder.php
  tests/framework/db/QueryBuilderTest.php
  tests/framework/db/QueryTest.php
Labels: type:bug

#13618 Reset outdated related models after AR update
  framework/CHANGELOG.md
  framework/db/BaseActiveRecord.php
  tests/data/ar/Department.php
  tests/data/ar/Dossier.php
  tests/data/ar/Employee.php
  tests/data/cubrid.sql
  tests/data/mssql.sql
  tests/data/mysql.sql
  tests/data/oci.sql
  tests/data/postgres.sql
  tests/data/sqlite.sql
  tests/framework/db/ActiveRecordTest.php
Labels: feature:db, status:under discussion, type:enhancement

#15203 Add support for tinyint as DB column type
  framework/CHANGELOG.md
  framework/db/ColumnSchemaBuilder.php
  framework/db/Schema.php
  framework/db/SchemaBuilderTrait.php
  framework/db/cubrid/QueryBuilder.php
  framework/db/mssql/QueryBuilder.php
  framework/db/mssql/Schema.php
  framework/db/mysql/QueryBuilder.php
  framework/db/mysql/Schema.php
  framework/db/oci/QueryBuilder.php
  framework/db/pgsql/QueryBuilder.php
  framework/db/sqlite/QueryBuilder.php
  framework/db/sqlite/Schema.php
  tests/data/cubrid.sql
  tests/data/mssql.sql
  tests/data/mysql.sql
  tests/data/oci.sql
  tests/data/postgres.sql
  tests/data/sqlite.sql
  tests/framework/db/QueryBuilderTest.php
  tests/framework/db/SchemaTest.php
  tests/framework/db/cubrid/SchemaTest.php
  tests/framework/db/oci/SchemaTest.php
  tests/framework/db/pgsql/SchemaTest.php
Labels: feature:db, type:bug

#13675 ExistValidator for relations
  framework/CHANGELOG.md
  framework/validators/ExistValidator.php
  tests/framework/validators/ExistValidatorTest.php
Labels: type:enhancement

#15650 Fixes #15272: removing type from script tag.
  framework/CHANGELOG.md
  framework/views/errorHandler/exception.php
  framework/web/View.php
  tests/framework/mail/BaseMailerTest.php
  tests/framework/web/ViewTest.php
Labels: type:enhancement

#15645 Fix #15644 checkboxList wrong checked
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: status:to be verified, type:bug

#15652 2.0.14 upgrade guide improvements
  framework/UPGRADE.md
Labels: type:docs

#15664 Check db driver have useMaster or not for calling.
  framework/validators/UniqueValidator.php
Labels: severity:important, type:bug

#15663 \yii\log\FileTarget directory creation is moved to export() method
  framework/CHANGELOG.md
  framework/log/FileTarget.php
  tests/framework/log/FileTargetTest.php
Labels: type:bug

#15668 Added `yii\db\ExpressionInterface` support to `yii\db\Command::batchInsert()`
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/QueryBuilder.php
  framework/db/oci/QueryBuilder.php
  framework/db/pgsql/QueryBuilder.php
  framework/db/sqlite/QueryBuilder.php
  tests/framework/db/CommandTest.php
  tests/framework/db/pgsql/CommandTest.php
  tests/framework/db/sqlite/CommandTest.php
Labels: type:enhancement

#15671 DocBlock fix for \yii\mail\MessageInterface
  framework/mail/MessageInterface.php
Labels: type:docs

#15701 Fix ExistValidator with targetRelation ignores filter (#15692)
  framework/CHANGELOG.md
  framework/validators/ExistValidator.php
  tests/framework/validators/ExistValidatorTest.php
Labels: type:bug

#15734 Fix #15656: Error in the documentation of widget theming
  docs/guide-es/output-theming.md
  docs/guide-ja/output-theming.md
  docs/guide-pt-BR/output-theming.md
  docs/guide-ru/output-theming.md
  docs/guide/output-theming.md
Labels: type:docs

#15742 Updated setActivePlaceholder to be consistent with activeLabel
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#15747 Fix #15678: attribute is not defined
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
  tests/js/tests/yii.activeForm.test.js
Labels: type:bug

#15733 Implemented \Traversable in ArrayExpression
  framework/CHANGELOG.md
  framework/db/ArrayExpression.php
  tests/framework/db/pgsql/ActiveRecordTest.php
Labels: PostgreSQL, type:enhancement

#15754 Correct table name in docs
  docs/guide/tutorial-yii-as-micro-framework.md
Labels: type:docs

#15746 Fix #15724: MigrateController::optionAliases() have 2 same keys
  framework/console/controllers/MigrateController.php
Labels: type:bug

#15730 Fixed Query::select()
  framework/CHANGELOG.md
  framework/db/Query.php
  tests/framework/db/QueryTest.php
Labels: severity:BC breaking, type:bug

#15700 Fix HttpAuthHeader
  framework/CHANGELOG.md
  framework/filters/auth/HttpHeaderAuth.php
  tests/framework/filters/auth/CompositeAuthTest.php
  tests/framework/web/UserIdentity.php
Labels: severity:BC breaking, type:bug

#15738 Fix ExistValidator is broken for NOSQL
  framework/CHANGELOG.md
  framework/validators/ExistValidator.php
Labels: severity:BC breaking, type:bug

#15318 Fix session_name(): Cannot change session name when session is active
  framework/CHANGELOG.md
  framework/web/Session.php
  tests/framework/web/session/SessionTest.php
Labels: php7, type:bug

#15764 Fixed yii\db\Command::upsert() for Cubrid/MSSQL/Oracle (fixes #15708)
  framework/CHANGELOG.md
  framework/db/cubrid/QueryBuilder.php
  framework/db/mssql/QueryBuilder.php
  framework/db/oci/QueryBuilder.php
  tests/data/mssql.sql
  tests/data/oci.sql
  tests/framework/db/cubrid/QueryBuilderTest.php
  tests/framework/db/mssql/QueryBuilderTest.php
  tests/framework/db/oci/QueryBuilderTest.php
Labels: MSSQL, Oracle, type:bug

#15789 fix complex example
  framework/db/conditions/BetweenColumnsCondition.php
Labels: type:docs

#15809 Fix #15383 drop PJAX
  docs/guide/README.md
  docs/guide/input-forms.md
  docs/guide/output-data-widgets.md
  docs/guide/start-installation.md
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/grid/ActionColumn.php
  framework/web/Controller.php
  framework/web/Request.php
  framework/web/Response.php
  framework/widgets/Pjax.php
  framework/widgets/PjaxAsset.php
  tests/framework/grid/ActionColumnTest.php
  tests/framework/web/RequestTest.php
  tests/framework/widgets/PjaxTest.php
Labels: type:task
