Repository yiisoft/yii2, pull requests merged in 2018-07, with the labels that each got.

#16370 Auto filter switch(#16365)
  framework/CHANGELOG.md
  framework/assets/yii.gridView.js
  framework/grid/GridView.php
  tests/js/tests/yii.gridView.test.js
Labels: JS

#16457 Fixes #16456: OptimisticLockBehavior omitting web HTML forms
  docs/guide/db-active-record.md
  framework/behaviors/OptimisticLockBehavior.php
  tests/framework/behaviors/OptimisticLockBehaviorTest.php
Labels: severity:important

#16487 Added circular reference detection in DI
  framework/CHANGELOG.md
  framework/di/CircularReferenceException.php
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
Labels: type:enhancement

#16495 Added method call support in DI and Yii::configure
  framework/BaseYii.php
  framework/CHANGELOG.md
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/stubs/QuxHolder.php
Labels: severity:important, type:enhancement

#15507 Fix #11389 Refactor Event Interface
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/base/ActionFilter.php
  framework/base/Component.php
  framework/base/Controller.php
  framework/base/Event.php
  framework/base/Model.php
  framework/base/Module.php
  framework/base/View.php
  framework/base/Widget.php
  framework/db/BaseActiveRecord.php
  framework/i18n/MessageSource.php
  framework/mail/BaseMailer.php
  framework/web/User.php
  framework/widgets/ActiveFieldEvent.php
  framework/widgets/ActiveForm.php
  tests/framework/ar/ActiveRecordTestTrait.php
  tests/framework/base/ComponentTest.php
  tests/framework/base/EventTest.php
  tests/framework/behaviors/AttributeBehaviorTest.php
  tests/framework/behaviors/AttributesBehaviorTest.php
  tests/framework/behaviors/BlameableBehaviorTest.php
  tests/framework/db/ActiveQueryTest.php
Labels: severity:BC breaking, type:enhancement

#12895 Use custom error action regardless of response format
  framework/CHANGELOG.md
  framework/web/ErrorHandler.php
Labels: status:under discussion, type:enhancement

#16555 Update caching data docs (#15901)
  docs/guide-ru/caching-data.md
  docs/guide/caching-data.md
Labels: type:docs

#16357 Fixes #16192: Extracted `getCacheKey()` protected method from `queryInternal()` protected method
  framework/CHANGELOG.md
  framework/db/Command.php
Labels: status:to be verified, type:enhancement

#16566 Intro yii some minor changes
  docs/guide-fr/intro-yii.md
Labels: type:docs

#16522 Allow jQuery 3.3
  composer.json
  framework/CHANGELOG.md
Labels: JS
