Repository yiisoft/yii2, pull requests merged in 2018-03, with the labels that each got.

#15805 Fixed has-error class to ActiveField div container when attribute nam…
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
  tests/framework/widgets/ActiveFieldTest.php
Labels: pr:request for unit tests

#15812 added autoloading path for yii (CLI) when installed from yii2-dev
  framework/yii
Labels: type:bug

#15848 Connection::getTransaction() adjust phpdoc to also return null
  framework/db/Connection.php
Labels: type:docs

#15840 Added tests for #15814
  framework/CHANGELOG.md
  framework/test/ActiveFixture.php
  framework/test/BaseActiveFixture.php
  framework/test/FileFixtureTrait.php
  tests/framework/test/ActiveFixtureTest.php
Labels: type:bug

#15851 Speed up fetching MySQL constraints (fixes #15776)
  framework/CHANGELOG.md
  framework/db/mysql/Schema.php
Labels: MySQL, type:bug

#15855 Fix PostgreSQL aray field typecast when $disableArraySupport is true
  framework/db/pgsql/ColumnSchema.php
Labels: type:bug

#15811 renderDynamic break
  framework/CHANGELOG.md
  framework/base/View.php
  tests/framework/base/ViewTest.php
Labels: type:bug

#15857 Fixed nesting of JsonExpression, ArrayExpression
  framework/CHANGELOG.md
  framework/db/ArrayExpression.php
  framework/db/JsonExpression.php
  framework/db/pgsql/JsonExpressionBuilder.php
  tests/framework/db/mysql/QueryBuilderTest.php
  tests/framework/db/pgsql/ActiveRecordTest.php
Labels: type:bug

#15859 15858 broken basehtml collecterrors with showallerrors true
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#15887 Adjust code sample to screenshot
  docs/guide/start-databases.md
Labels: type:docs

#15868 Fixed JsonExpressionBuilder to cast JSON explicitly
  framework/CHANGELOG.md
  framework/db/mysql/JsonExpressionBuilder.php
  tests/framework/db/mysql/QueryBuilderTest.php
Labels: MySQL, type:bug

#15890 Cache Flushing as separate section
  docs/guide/caching-data.md
Labels: type:docs

#15878 Fix migration with a comment containing an apostrophe
  framework/CHANGELOG.md
  framework/db/mysql/QueryBuilder.php
  tests/framework/db/mysql/QueryBuilderTest.php
Labels: feature:db, type:bug

#15930 CacheableWidgetBehaviorTest enhancements
  tests/framework/behaviors/CacheableWidgetBehaviorTest.php
Labels: type:test

#15960 ja translation updates and encoding fix
  docs/guide-ja/glossary.md
  docs/guide-ja/input-form-javascript.md
  docs/guide-ja/output-data-providers.md
  docs/guide-ja/output-data-widgets.md
  docs/guide-ja/rest-error-handling.md
  docs/guide-ja/rest-quick-start.md
  docs/guide-ja/rest-resources.md
  docs/guide-ja/rest-routing.md
  docs/internals-ja/pull-request-qa.md
Labels: type:docs

#15967 Issue #15957: fix of travis builds
  .travis.yml
Labels: type:test

#15969 Guide ja 180324 updates
  docs/guide-ja/runtime-requests.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/security-authorization.md
  docs/guide-ja/security-best-practices.md
  docs/guide-ja/security-overview.md
  docs/guide-ja/start-databases.md
  docs/guide-ja/start-forms.md
  docs/guide-ja/start-installation.md
  docs/guide-ja/start-looking-ahead.md
  docs/guide-ja/start-prerequisites.md
Labels: type:docs

#15979 framework/messages/ja/yii.php updated [skip ci]
  framework/messages/ja/yii.php
Labels: type:docs

#15978 docs/guide-ja updats [ci skip]
  docs/guide-ja/README.md
  docs/guide-ja/structure-application-components.md
  docs/guide-ja/structure-assets.md
  docs/guide-ja/structure-modules.md
  docs/guide-ja/structure-widgets.md
  docs/guide-ja/test-acceptance.md
  docs/guide-ja/test-environment-setup.md
  docs/guide-ja/test-fixtures.md
  docs/guide-ja/test-functional.md
  docs/guide-ja/test-overview.md
  docs/guide-ja/test-unit.md
  docs/guide-ja/tutorial-console.md
  docs/guide-ja/tutorial-core-validators.md
  docs/guide-ja/tutorial-performance-tuning.md
  docs/guide-ja/tutorial-shared-hosting.md
  docs/guide-ja/tutorial-template-engines.md
  docs/guide-ja/tutorial-yii-as-micro-framework.md
Labels: type:docs

#15974 docs/guide/structure-modules.md small fix
  docs/guide/structure-modules.md
  docs/guide/test-fixtures.md
Labels: type:docs

#15982 Update db-dao.md
  docs/guide-es/db-dao.md
Labels: type:docs

#15938 added docs about Docker
  docs/guide/README.md
  docs/guide/tutorial-docker.md
Labels: type:docs

#15989 Issue #15988: Fixed bash completion
  contrib/completion/bash/yii
  framework/CHANGELOG.md
Labels: type:bug

#15997 Add php-intl dependency info for SluggableBehavior
  framework/behaviors/SluggableBehavior.php
Labels: type:docs

#16002 Fixes #14660: fixed synchronous DbCache::set() with the same key
  framework/CHANGELOG.md
  framework/caching/DbCache.php
  tests/framework/caching/DbCacheTest.php
Labels: type:bug

#16013 Fixes #16010: fixed `ContentNegotiator` behavior when GET parameters contain an array
  framework/CHANGELOG.md
  framework/filters/ContentNegotiator.php
  tests/framework/filters/ContentNegotiatorTest.php
Labels: type:bug

#16006 Fix/forwarded host
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: type:bug

#16018 docs/internals-ja revised [ci skip]
  docs/internals-ja/README.md
  docs/internals-ja/automation.md
  docs/internals-ja/bc.md
  docs/internals-ja/core-code-style.md
  docs/internals-ja/design-decisions.md
  docs/internals-ja/git-workflow.md
  docs/internals-ja/project-organization.md
  docs/internals-ja/pull-request-qa.md
  docs/internals-ja/release.md
  docs/internals-ja/report-an-issue.md
  docs/internals-ja/translation-workflow.md
  docs/internals-ja/versions.md
  docs/internals-ja/view-code-style.md
Labels: type:docs
