Repository yiisoft/yii2, pull requests merged in 2018-09, with the labels that each got.

#16690 Fixing travis
  framework/CHANGELOG.md
  framework/assets/yii.validation.js
  framework/db/ActiveQuery.php
  framework/di/Container.php
  tests/js/tests/yii.validation.test.js
Labels: type:bug

#16440 Fixed exception class in yii\di\Container (#15802)
  framework/CHANGELOG.md
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
Labels: type:bug

#15308 Bug #5341: HasMany via two relations
  framework/CHANGELOG.md
  framework/db/ActiveRelationTrait.php
  tests/framework/db/ActiveQueryTest.php
Labels: feature:db, status:to be verified, type:bug

#16698 docs/guide-ja updated [skip ci]
  docs/guide-ja/caching-data.md
  docs/guide-ja/db-active-record.md
  docs/guide-ja/input-validation.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/start-databases.md
  docs/guide-ja/start-installation.md
  docs/guide-ja/tutorial-core-validators.md
Labels: type:docs

#16704 docs/guide/db-active-record.md fixed [ci skip]
  docs/guide/db-active-record.md
Labels: type:docs

#16689 Add normalize max length for active input(#16680)
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#16712 fix structure assets doc rus
  docs/guide-ru/structure-assets.md
Labels: type:docs

#16713 Added role attributes to the input options (#14368)
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
  tests/framework/widgets/ActiveFieldTest.php
Labels: type:bug

#16732 Fix submit form
  framework/CHANGELOG.md
  framework/assets/yii.js
Labels: JS, pr:request for unit tests

#16722 Pressing "Enter" key does not depend on the option "filterOnFocusOut"
  framework/CHANGELOG.md
  framework/assets/yii.gridView.js
  tests/js/tests/yii.gridView.test.js
Labels: type:bug
