Repository yiisoft/yii2, pull requests merged in 2018-05, with the labels that each got.

#16191 Fixed `yii\helpers\Inflector::camel2words()` to work with UTF-8
  framework/CHANGELOG.md
  framework/helpers/BaseInflector.php
  tests/framework/helpers/InflectorTest.php
  tests/framework/widgets/DetailViewTest.php
Labels: type:bug

#16231 Update Vietnamese translate
  docs/guide-vi/structure-application-components.md
  docs/guide-vi/structure-applications.md
  docs/guide-vi/structure-controllers.md
  docs/guide-vi/structure-entry-scripts.md
  docs/guide-vi/structure-models.md
Labels: type:docs

#16246 BaseAR now catches errors in __isset
  .travis.yml
  framework/CHANGELOG.md
  framework/db/BaseActiveRecord.php
  tests/data/ar/Cat.php
  tests/framework/db/ActiveRecordTest.php
Labels: type:bug

#16211 Fixed relative paths inside themed and localized files
  framework/CHANGELOG.md
  framework/base/View.php
  tests/framework/base/ViewTest.php
Labels: type:bug

#16206 [ENH] introduce yii\behaviors\OptimisticLockBehavior to avoid #9133 bug
  docs/guide/db-active-record.md
  framework/CHANGELOG.md
  framework/behaviors/OptimisticLockBehavior.php
  framework/db/BaseActiveRecord.php
  tests/framework/behaviors/OptimisticLockBehaviorTest.php
Labels: type:enhancement

#16217 Fix Appveyor
  .appveyor.yml
  framework/CHANGELOG.md
  framework/console/controllers/HelpController.php
Labels: type:test

#15464 docs enhancement
  framework/base/Controller.php
Labels: type:docs

#16277 fix bug: when use ActiveQuery subquery
  framework/db/Query.php
Labels: type:bug

#16292 Fix class namespace
  framework/CHANGELOG.md
  framework/filters/Cors.php
Labels: type:bug

#15548 rbac fix migration
  framework/CHANGELOG.md
  framework/rbac/migrations/m180523_151638_rbac_updates_indexes_without_prefix.php
Labels: type:bug

#16337 docs/guide-ja/structure-assets.md updated [ci skip]
  docs/guide-ja/structure-assets.md
Labels: type:docs

#16272 Update m170907_052038_rbac_add_index_on_auth_assignment_user_id.php
  framework/rbac/migrations/m170907_052038_rbac_add_index_on_auth_assignment_user_id.php
Labels: type:bug

#16288 Resolved issue #16252.
  framework/CHANGELOG.md
  framework/base/DynamicModel.php
  tests/framework/base/DynamicModelTest.php
Labels: type:bug

#16326 Fixed #16104 bug: use schema name from table path in PostgreSQL QueryBuilder::dropIndex()
  framework/CHANGELOG.md
  framework/db/pgsql/QueryBuilder.php
  tests/framework/db/pgsql/QueryBuilderTest.php
Labels: PostgreSQL, type:bug
