Repository yiisoft/yii2, pull requests merged in 2019-05, with the labels that each got.

#17234 Fixed bug with integer attributes
  framework/CHANGELOG.md
  framework/validators/Validator.php
  tests/framework/validators/ValidatorTest.php
Labels: type:bug

#17315 Closes #16509. Remove cut parameter of the wordwrap function.
  framework/CHANGELOG.md
  framework/helpers/BaseConsole.php
Labels: status:ready for merge

#17318 Closes #17299. Fix adding of input error class in ActiveField::widget
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
  tests/framework/widgets/ActiveFieldTest.php
Labels: type:bug

#17272 Translate output client scripts into russian
  docs/guide-ru/README.md
  docs/guide-ru/output-client-scripts.md
Labels: type:docs
