Repository yiisoft/yii2, pull requests merged in 2019-06, with the labels that each got.

#17330 Fixes #17328 Added mime aliases for BMP and SVG files
  framework/CHANGELOG.md
  framework/helpers/mimeAliases.php
Labels: type:bug

#17338 Fixes #17336: Fixed wildcard matching in Event::hasHandlers()
  framework/CHANGELOG.md
  framework/base/Event.php
  tests/framework/base/EventTest.php
Labels: type:bug

#17342 Issue #17341 Fix error from yii.activeForm.js in strict mode
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
Labels: type:bug

#17345 Improve quoteColumnName() performance
  framework/CHANGELOG.md
  framework/db/Connection.php
Labels: status:ready for merge

#17353 Added support for SameSite Cookie option
  docs/guide/runtime-sessions-cookies.md
  docs/guide/security-best-practices.md
  framework/CHANGELOG.md
  framework/web/Cookie.php
  framework/web/Response.php
  framework/web/Session.php
Labels: severity:security, status:under development

#17344 Improve performance of select() and addSelect()
  framework/CHANGELOG.md
  framework/db/Query.php
  framework/db/QueryBuilder.php
  tests/framework/db/QueryBuilderTest.php
  tests/framework/db/QueryTest.php
Labels: status:ready for merge

#17358 Allow callable objects to be set to \yii\filters\AccessRule::$roleParams
  framework/CHANGELOG.md
  framework/filters/AccessRule.php
  tests/framework/filters/AccessRuleTest.php
Labels: type:bug

#17361 Closes #17070. Strip invalid character from fallback file name
  framework/CHANGELOG.md
  framework/web/Response.php
  tests/framework/web/ResponseTest.php
Labels: type:bug

#17367 Closes #16565. Add missing parts of the context message.
  framework/CHANGELOG.md
  framework/log/Target.php
  tests/framework/log/TargetTest.php
Labels: type:bug

#17339 Fixes #12080. Whenever updateInputs is called, it will trigger 'after…
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
  tests/js/tests/yii.activeForm.test.js
Labels: status:code review, type:bug

#17375 Closes #17372. Fix documentation for the `ArrayHelper::multisort()`
  docs/guide/helper-array.md
  framework/helpers/BaseArrayHelper.php
Labels: type:docs

#17356 Fixes mssql schema to detect sizes of string fields
  framework/CHANGELOG.md
  framework/db/Connection.php
  framework/db/mssql/Schema.php
  tests/framework/db/SchemaTest.php
  tests/framework/db/mssql/SchemaTest.php
Labels: MSSQL, type:bug

#17373 Fixes #17332: Trigger 'change' for checkboxes in GridView
  framework/CHANGELOG.md
  framework/assets/yii.gridView.js
  tests/js/tests/yii.gridView.test.js
Labels: JS, status:code review

#17380 Closes #16411. Fix windows tests
  .appveyor.yml
  framework/console/controllers/MessageController.php
  tests/TestCase.php
  tests/framework/helpers/ConsoleTest.php
  tests/framework/web/ViewTest.php
Labels: status:code review, type:test

#17385 Update input-file-upload.md RUS
  docs/guide-ru/input-file-upload.md
  docs/guide/input-file-upload.md
Labels: type:docs

#17388 Closes #16394. Fix issues in `migrate/create`
  framework/CHANGELOG.md
  framework/console/controllers/MigrateController.php
  framework/views/addColumnMigration.php
  tests/data/console/migrate_create/add_two_columns_test.php
  tests/data/console/migrate_create/create_field_with_colon_default_values.php
  tests/framework/console/controllers/MigrateControllerTest.php
Labels: status:ready for merge

#17403 Fix DISTINCT ON query generation
  framework/CHANGELOG.md
  framework/db/Query.php
  tests/framework/db/QueryTest.php
Labels: status:code review

#17402 Closes #17325. Add view detection for MySQL.
  framework/CHANGELOG.md
  framework/console/controllers/MigrateController.php
  tests/TestCase.php
  tests/framework/console/controllers/MigrateControllerTest.php
Labels: MySQL, status:code review
