Repository yiisoft/yii2, pull requests merged in 2019-11, with the labels that each got.

#17648 Handle empty row column arrays
  framework/CHANGELOG.md
  framework/console/widgets/Table.php
  tests/framework/console/widgets/TableTest.php
Labels: type:bug

#17657 Fix errors from missing $schema in RBAC init file
  framework/CHANGELOG.md
  framework/rbac/migrations/m140506_102106_rbac_init.php
Labels: MSSQL, type:bug

#17632 Fixed a bug with the file russian name "x.jpg"
  framework/CHANGELOG.md
  framework/web/MultipartFormDataParser.php
  tests/framework/web/MultipartFormDataParserTest.php
Labels: type:bug

#17663 Bug fix in method description
  framework/data/Sort.php
Labels: type:docs

#17670 Fix wrong overriden application core component configuration when uses Yii3 style
  framework/CHANGELOG.md
  framework/base/Application.php
Labels: pr:request for unit tests, type:bug

#17689 Bug #17685: up and down methods now using proper "db" component
  framework/CHANGELOG.md
  framework/rbac/migrations/m180523_151638_rbac_updates_indexes_without_prefix.php
Labels: type:bug
