Repository yiisoft/yii2, pull requests merged in 2019-03, with the labels that each got.

#17086 fix checkdns gives false positive
  framework/CHANGELOG.md
  framework/validators/EmailValidator.php
Labels: type:bug

#17124 Fix #17123
  framework/CHANGELOG.md
  framework/console/controllers/FixtureController.php
Labels: type:bug

#17149 fix aliases rendering
  framework/CHANGELOG.md
  framework/console/controllers/HelpController.php
  tests/framework/console/ControllerTest.php
  tests/framework/console/FakeHelpControllerWithoutOutput.php
Labels: type:bug

#17011 AR: pass input options to widget
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
  tests/framework/widgets/ActiveFieldTest.php
Labels: type:bug

#17188 Handle DB session callback custom fields before session closed
  framework/CHANGELOG.md
  framework/web/DbSession.php
  framework/web/MultiFieldSession.php
  tests/framework/web/session/AbstractDbSessionTest.php
Labels: type:bug

#17152 Bug #15216: Fix a link for open files in IDE
  framework/CHANGELOG.md
  framework/views/errorHandler/callStackItem.php
  framework/views/errorHandler/exception.php
Labels: type:bug

#17215 Set allowed_classes => false when unserializing cookie data
  framework/CHANGELOG.md
  framework/web/Request.php
Labels: severity:security, type:enhancement

#16928 Fixed issue #16335 - added support netmask in access rule
  framework/CHANGELOG.md
  framework/filters/AccessRule.php
  tests/framework/filters/AccessRuleTest.php
Labels: status:code review, type:bug

#17065 16158 fix multiple select validation
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
Labels: status:code review, type:bug

#16368 kB instead of KB
  framework/i18n/Formatter.php
  framework/messages/ar/yii.php
  framework/messages/bs/yii.php
  framework/messages/cs/yii.php
  framework/messages/de/yii.php
  framework/messages/el/yii.php
  framework/messages/es/yii.php
  framework/messages/fa/yii.php
  framework/messages/fi/yii.php
  framework/messages/fr/yii.php
  framework/messages/hy/yii.php
  framework/messages/it/yii.php
  framework/messages/ja/yii.php
  framework/messages/ka/yii.php
  framework/messages/kz/yii.php
  framework/messages/lt/yii.php
  framework/messages/lv/yii.php
  framework/messages/ms/yii.php
  framework/messages/nb-NO/yii.php
  framework/messages/nl/yii.php
  framework/messages/pl/yii.php
  framework/messages/pt-BR/yii.php
  framework/messages/ru/yii.php
  framework/messages/sk/yii.php
  framework/messages/sl/yii.php
  framework/messages/sv/yii.php
  framework/messages/tg/yii.php
  framework/messages/tr/yii.php
  framework/messages/uk/yii.php
  framework/messages/uz/yii.php
  framework/messages/zh-CN/yii.php
  framework/messages/zh-TW/yii.php
  tests/framework/i18n/FormatterNumberTest.php
Labels: status:code review, type:bug

#17127 `yii\db\ActiveRecord::findOne()` now accepts table aliases
  framework/CHANGELOG.md
  framework/db/ActiveRecord.php
  tests/framework/db/ActiveRecordTest.php
Labels: status:code review, type:bug

#17228 Added upgrade step for Yii 2.0.17 about yii\web\DbSession
  framework/UPGRADE.md
Labels: type:docs

#17229 Fixed (#17220)
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
Labels: pr:request for unit tests, type:bug
