Repository yiisoft/yii2, pull requests merged in 2019-12, with the labels that each got.

#17702 Throw BadRequestHttpException when request params can't be bound to controller action
  framework/CHANGELOG.md
  framework/web/Controller.php
  tests/framework/web/ControllerTest.php
  tests/framework/web/FakePhp7Controller.php
Labels: type:bug

#17703 Fixed Error Handler to clear view tags, scripts, etc. when rendering error action view
  framework/CHANGELOG.md
  framework/web/ErrorHandler.php
  tests/data/controllers/TestController.php
  tests/framework/web/ErrorActionTest.php
  tests/framework/web/ErrorHandlerTest.php
Labels: type:enhancement

#17709 Use release PHP 7.4 in tests
  .travis.yml
Labels: type:test

#17719 Fix GridView JS test to click on all elements in a group instead of only first element
  tests/js/tests/yii.gridView.test.js
Labels: JS, type:test

#17723 Fixed for PHP 7.4 without tests
  .travis.yml
  framework/CHANGELOG.md
  framework/base/Model.php
  framework/db/pgsql/Schema.php
  framework/web/Controller.php
Labels: php7

#17721 fix BaseMailerTest class
  tests/framework/mail/BaseMailerTest.php
Labels: type:test

#17688 Allow indexBy to include a table alias
  framework/CHANGELOG.md
  framework/db/Query.php
  tests/framework/db/QueryTest.php
Labels: type:bug

#17720 Fix yii3 di
  framework/BaseYii.php
  framework/CHANGELOG.md
  framework/base/Application.php
  framework/di/ServiceLocator.php
  tests/framework/BaseYiiTest.php
  tests/framework/di/ServiceLocatorTest.php
  tests/framework/di/stubs/FooBaz.php
Labels: type:bug

#17731 Fix MemCache duration normalization to avoid memcached/system timestamp mismatch
  framework/CHANGELOG.md
  framework/caching/MemCache.php
Labels: type:bug

#17676 Implement RFC 7239 `Forwarded` header parsing
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: severity:security, status:code review

#17697 InConditionBuilder proper null handling
  framework/CHANGELOG.md
  framework/db/conditions/InConditionBuilder.php
  tests/framework/db/QueryBuilderTest.php
Labels: status:ready for merge

#17741 fix #17740: `yii\helpers\BaseInflector::slug()` doesn't replace multip…
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/helpers/BaseInflector.php
  tests/framework/helpers/InflectorTest.php
Labels: type:bug

#17733 Forwarded RFC 7239 fix
  docs/guide/runtime-requests.md
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: status:code review

#17745 Fixed regexp
  framework/CHANGELOG.md
  framework/db/pgsql/QueryBuilder.php
  tests/framework/db/pgsql/QueryBuilderTest.php
Labels: type:bug

#17751 Fix bug with current_time microseconds
  framework/CHANGELOG.md
  framework/db/mysql/Schema.php
  tests/framework/db/mysql/SchemaTest.php
Labels: status:code review, type:bug

#17762 PHP 7.4: Remove special condition for converting PHP errors to exceptions
  framework/CHANGELOG.md
  framework/base/ErrorHandler.php
Labels: type:bug

#17761 Dispatcher::dispatch() target crash php 7.x fix #17749
  framework/CHANGELOG.md
  framework/log/Dispatcher.php
  tests/framework/log/DispatcherTest.php
  tests/framework/log/mocks/TargetMock.php
  tests/framework/log/mocks/typed_error.php
Labels: php7, status:code review
