Repository yiisoft/yii2, pull requests merged in 2019-09, with the labels that each got.

#17525 IE11 Ajax redirect 308 fixes #17434
  framework/CHANGELOG.md
  framework/web/Response.php
  tests/framework/web/ResponseTest.php
  tests/framework/web/mocks/TestRequestComponent.php
Labels: status:code review

#17537 Fix 17449: Moved Check of column-definition behind Comment when adding a comment to a column
  framework/CHANGELOG.md
  framework/db/mysql/QueryBuilder.php
  tests/README.md
  tests/data/config-docker.php
  tests/docker-compose.yml
  tests/framework/db/mysql/QueryBuilderTest.php
Labels: status:code review

#17540 Fix #16531: check if set_time_limit() exists before calling it
  framework/CHANGELOG.md
  framework/web/Response.php
Labels: type:bug

#17551 docs/guide-ja updated
  docs/guide-ja/db-migrations.md
  docs/guide-ja/helper-array.md
  docs/guide-ja/input-file-upload.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/security-best-practices.md
  docs/guide-ja/structure-assets.md
  docs/guide-ja/structure-modules.md
  docs/guide-ja/test-fixtures.md
  docs/guide-ja/tutorial-console.md
  docs/guide/runtime-sessions-cookies.md
  docs/guide/security-best-practices.md
Labels: type:docs

#17555 Fix regular expression illegal character #17434
  framework/CHANGELOG.md
  framework/web/Response.php
Labels: type:bug

#17550 Fix #17549: Add `yii\db\ExpressionInterface` support to `SimpleConditionBuilder`
  framework/CHANGELOG.md
  framework/db/conditions/SimpleConditionBuilder.php
  tests/framework/db/QueryBuilderTest.php
Labels: type:bug

#17547 #17539 fix error when using `batch()` with `indexBy()` with MSSQL
  framework/CHANGELOG.md
  framework/db/BatchQueryResult.php
  tests/framework/db/BatchQueryResultTest.php
Labels: status:ready for merge, type:bug

#13712 Adding IIS Configurations
  docs/guide/start-installation.md
Labels: type:docs

#17581 docs/guide-ja updated [ci skip]
  docs/guide-ja/output-data-widgets.md
  docs/guide-ja/start-installation.md
Labels: type:docs
