Repository yiisoft/yii2, pull requests merged in 2019-10, with the labels that each got.

#17582 update db-dao
  docs/guide/db-dao.md
Labels: type:docs

#17591 Fix #17533: Fix mutex testRetryAcquire() on Windows
  tests/framework/mutex/RetryAcquireTraitTest.php
Labels: type:test

#17574 Request::getUserIP() secure fix #17573
  framework/CHANGELOG.md
  framework/validators/IpValidator.php
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: severity:security

#17583 Changed ActiveField __toString method to catch all php 7 error types.
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
Labels: php7, type:bug

#17593 request::getUserHost() and request::getUserIp() fix #17521 #17573
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: status:code review

#17596 Already resolved IP: doc added #17521
  docs/guide/runtime-requests.md
Labels: type:docs

#17586 Fix #17585: @calendar param included in Formatter Yii:t() calls
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
  tests/framework/i18n/FormatterTest.php
Labels: status:code review

#17604 fix yiisoft#17602 suppress ErrorException if dns_get_record returned f…
  framework/CHANGELOG.md
  framework/validators/EmailValidator.php
Labels: type:bug

#17606 Proposal: do not publish dummy asset bundle
  framework/CHANGELOG.md
  framework/web/AssetManager.php
Labels: type:bug

#17611 (fix) Unterminated JS statement in views/ErrorHandler/exception.php
  framework/views/errorHandler/exception.php
Labels: JS

#17607 Added Yii 3 DI compatibility
  docs/guide/concept-di-container.md
  framework/BaseYii.php
  framework/CHANGELOG.md
  framework/di/Container.php
  framework/di/ServiceLocator.php
  tests/framework/BaseYiiTest.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/InstanceTest.php
  tests/framework/di/stubs/QuxFactory.php
Labels: type:docs, type:enhancement

#17608 Issue 17597 postgresql12
  framework/CHANGELOG.md
  framework/db/pgsql/ColumnSchema.php
  framework/db/pgsql/Schema.php
  tests/data/postgres.sql
  tests/data/postgres10.sql
  tests/data/postgres12.sql
  tests/framework/db/CommandTest.php
  tests/framework/db/pgsql/QueryBuilderTest.php
  tests/framework/db/pgsql/SchemaTest.php
Labels: PostgreSQL, status:code review

#17625 Add support for boolean data attributes to Html::renderTagAttributes()
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#17480 Bug #8225: Fixed ajax Validation with checkboxList only on first select
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
  tests/js/tests/yii.activeForm.test.js
Labels: JS, type:bug
