Repository yiisoft/yii2, pull requests merged in 2019-08, with the labels that each got.

#17489 Closes #17486. Fix error when using `batch()` without `$db` parameter…
  framework/CHANGELOG.md
  framework/db/BatchQueryResult.php
  tests/framework/db/BatchQueryResultTest.php
Labels: type:bug

#17488 Fix minor typos in fixture guide
  docs/guide/test-fixtures.md
Labels: type:docs

#17490 #17473 fix simple condition build
  framework/CHANGELOG.md
  framework/db/conditions/SimpleConditionBuilder.php
  tests/framework/db/QueryBuilderTest.php
Labels: status:code review

#17250 17223 detach behavior event
  framework/CHANGELOG.md
  framework/base/Behavior.php
  tests/framework/base/ComponentTest.php
  tests/framework/base/ModelTest.php
  tests/framework/base/stub/AnonymousComponentClass.php
Labels: status:code review

#17496 Update structure-modules.md
  docs/guide-ru/structure-modules.md
Labels: status:under development, type:docs

#17523 Fixed regular expression escaping and simpler condition in `Controlle…
  framework/CHANGELOG.md
  framework/base/Controller.php
  tests/framework/base/ControllerTest.php
Labels: status:ready for merge

#17526 17355 pjax after request bug 3
  framework/CHANGELOG.md
  framework/widgets/Pjax.php
Labels: status:ready for merge

#17531 16305 filevalidator case insensitive fix
  framework/CHANGELOG.md
  framework/validators/FileValidator.php
  tests/framework/validators/FileValidatorTest.php
Labels: status:ready for merge, type:bug

#17534 Fix #17522: `DbManager::isEmptyUserId()` is now protected
  framework/CHANGELOG.md
  framework/rbac/DbManager.php
Labels: type:bug
