Repository yiisoft/yii2, pull requests merged in 2020-11, with the labels that each got.

#18344 Documentation redirects
  docs/guide/caching-data.md
  docs/guide/caching-fragment.md
  docs/guide/concept-aliases.md
  docs/guide/concept-behaviors.md
  docs/guide/concept-configurations.md
  docs/guide/concept-di-container.md
  docs/guide/concept-service-locator.md
  docs/guide/db-active-record.md
  docs/guide/db-dao.md
  docs/guide/db-migrations.md
  docs/guide/db-query-builder.md
  docs/guide/helper-overview.md
  docs/guide/input-forms.md
  docs/guide/input-validation.md
  docs/guide/intro-upgrade-from-v1.md
  docs/guide/output-client-scripts.md
  docs/guide/output-data-providers.md
  docs/guide/output-data-widgets.md
  docs/guide/output-formatting.md
  docs/guide/rest-quick-start.md
  docs/guide/rest-resources.md
  docs/guide/runtime-logging.md
  docs/guide/runtime-requests.md
  docs/guide/runtime-responses.md
  docs/guide/security-authorization.md
  docs/guide/security-overview.md
  docs/guide/start-installation.md
  docs/guide/structure-applications.md
  docs/guide/structure-assets.md
  docs/guide/structure-controllers.md
  docs/guide/structure-extensions.md
  docs/guide/structure-models.md
  docs/guide/structure-modules.md
  docs/guide/structure-views.md
  docs/guide/tutorial-console.md
  docs/guide/tutorial-i18n.md
  docs/guide/tutorial-yii-integration.md
Labels: type:docs

#18369 Fix for #18368
  framework/db/ActiveRelationTrait.php
Labels: type:docs

#18370 Null in data filter
  framework/CHANGELOG.md
  framework/data/ActiveDataFilter.php
  framework/data/DataFilter.php
  tests/framework/data/ActiveDataFilterTest.php
  tests/framework/data/DataFilterTest.php
Labels: type:enhancement

#18379 Fix not taking default value when unable to resolve abstract class via DI container
  framework/CHANGELOG.md
  framework/di/Container.php
  framework/di/Instance.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/InstanceTest.php
  tests/framework/di/stubs/AbstractColor.php
  tests/framework/di/stubs/Alpha.php
  tests/framework/di/stubs/Color.php
Labels: type:bug

#18382 Add maxlength attribute to text filter for #18200 issue
  framework/CHANGELOG.md
  framework/grid/DataColumn.php
  tests/data/base/Singer.php
  tests/framework/grid/DataColumnTest.php
Labels: type:enhancement

#18387 Fixed typo in test-environment-setup.md
  docs/guide-ru/test-environment-setup.md
Labels: type:docs

#18391 added inherit doc as it has to return TRUE
  framework/console/Controller.php
Labels: status:code review, type:docs

#18397 Fix types in Controller and View classes
  framework/base/Controller.php
  framework/base/View.php
Labels: type:docs

#18396 Throw InvalidConfigException when failed to instantiate class via DI container
  framework/CHANGELOG.md
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/stubs/Kappa.php
  tests/framework/di/stubs/Zeta.php
Labels: type:bug

#18394 Add support for setting Response::$stream to a callable
  framework/CHANGELOG.md
  framework/web/Response.php
Labels: status:code review, type:enhancement

#18389 Fix content body response on 304 code for #18199 issue
  framework/CHANGELOG.md
  framework/web/Response.php
  tests/framework/web/ResponseTest.php
Labels: status:code review

#18386 Fix activeForm.js validatingCssClass selector
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
Labels: JS, status:code review, type:bug

#18385 Add ci-oracle and fixed tests fails.
  .github/workflows/ci-oracle.yml
  tests/data/ar/Customer.php
  tests/data/config.php
  tests/framework/ar/ActiveRecordTestTrait.php
  tests/framework/db/ActiveRecordTest.php
  tests/framework/db/CommandTest.php
  tests/framework/db/ConnectionTest.php
  tests/framework/db/QueryBuilderTest.php
  tests/framework/db/QueryTest.php
  tests/framework/db/oci/ActiveRecordTest.php
  tests/framework/db/oci/CommandTest.php
  tests/framework/db/oci/ConnectionTest.php
  tests/framework/db/oci/QueryBuilderTest.php
  tests/framework/db/oci/QueryTest.php
  tests/framework/db/oci/SchemaTest.php
  tests/framework/db/oci/UniqueValidatorTest.php
  tests/framework/validators/ExistValidatorTest.php
  tests/framework/validators/UniqueValidatorTest.php
Labels: Oracle, feature:db, status:code review

#18393 Update ActiveRecord.php
  framework/CHANGELOG.md
  framework/db/ActiveRecord.php
Labels: type:bug

#18384 rbac's generated file's EOL-characters fixed #18383
  framework/CHANGELOG.md
  framework/rbac/PhpManager.php
Labels: type:bug

#18407 Fix #18406 - avoid PDOExceptions when working with autocommitted transactions
  framework/CHANGELOG.md
  framework/db/Transaction.php
  tests/framework/db/mysql/ConnectionTest.php
Labels: status:code review, type:bug
