Repository yiisoft/yii2, pull requests merged in 2020-07, with the labels that each got.

#18144 fixed GitLab build
  .gitlab-ci.yml
Labels: type:test

#18147 Fixed parameters binding for mysql when prepare emulation is off
  framework/CHANGELOG.md
  framework/db/mysql/Schema.php
Labels: MySQL, type:bug

#18137 Support for composite file extension validation
  framework/CHANGELOG.md
  framework/assets/yii.validation.js
  framework/validators/FileValidator.php
  tests/framework/validators/FileValidatorTest.php
  tests/framework/validators/data/mimeType/test.tar.xz
Labels: status:code review

#18151 Added `Mutex::isAcquired()` to check if lock is currently acquired
  framework/CHANGELOG.md
  framework/mutex/Mutex.php
  tests/framework/mutex/MutexTestTrait.php
Labels: status:ready for adoption, type:enhancement

#18152 Bug #18086: Fix accessing public properties of `ArrayAccess` via `ArrayHelper::getValue()`
  framework/CHANGELOG.md
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: status:ready for merge, type:bug

#18062 Fixing validating array values separately
  docs/guide-pl/input-validation.md
  docs/guide/input-validation.md
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/validators/EachValidator.php
  framework/validators/InlineValidator.php
  framework/validators/Validator.php
  tests/data/base/Speaker.php
  tests/data/validators/models/FakedValidationModel.php
  tests/framework/validators/EachValidatorTest.php
  tests/framework/validators/ValidatorTest.php
Labels: status:code review

#18173 fix for issue yiisoft#18170
  framework/CHANGELOG.md
  framework/console/Controller.php
  tests/framework/console/ControllerTest.php
  tests/framework/console/FakeController.php
Labels: status:code review, type:bug

#18176 Fix for #18171. Changed case of columns names in sql query for findConstraints
  framework/CHANGELOG.md
  framework/db/mysql/Schema.php
Labels: status:code review, type:bug

#18185 Update BaseHtml and Formatter typehints
  framework/helpers/BaseHtml.php
  framework/i18n/Formatter.php
Labels: status:code review, type:docs

#18182 Added support for yii\db\Expression in ActiveRecord::findByCondition()
  framework/CHANGELOG.md
  framework/db/ActiveRecord.php
  framework/db/ActiveRecordInterface.php
  framework/db/BaseActiveRecord.php
  tests/framework/ar/ActiveRecordTestTrait.php
Labels: status:code review, type:bug

#18190 Fix #18189: Fix "Invalid parameter number" in `yii\rbac\DbManager::re…
  framework/CHANGELOG.md
  framework/rbac/DbManager.php
Labels: type:bug
