Repository yiisoft/yii2, pull requests merged in 2020-12, with the labels that each got.

#18425 Adding return type int to queryScalar method docs #18424
  framework/db/Command.php
  framework/db/Query.php
Labels: type:docs

#18427 #18287 The OUTPUT got SQL syntax error if the column name is MSSQL keyword e.g key.
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  tests/framework/db/mssql/QueryBuilderTest.php
Labels: MSSQL, status:code review, type:bug

#18429 Fix #18426 error when url route is empty in `yii\widgets\Menu`
  framework/CHANGELOG.md
  framework/widgets/Menu.php
Labels: status:ready for merge, type:bug

#18342 fix yii migrate exit code not correct
  framework/CHANGELOG.md
  framework/console/controllers/BaseMigrateController.php
  tests/framework/console/controllers/MigrateControllerTest.php
  tests/framework/console/controllers/MigrateControllerTestTrait.php
Labels: status:code review

#18432 Negative timezone in tests for date-only validation with non-UTC timezone
  tests/framework/validators/DateValidatorTest.php
Labels: type:test

#18400 Reset parent module
  framework/CHANGELOG.md
  framework/base/Module.php
  tests/framework/base/ApplicationTest.php
  tests/framework/base/ModuleTest.php
Labels: status:code review, type:bug

#18434 Fix eager loading Active Record relations when relation key is a subject to a type-casting behavior
  framework/CHANGELOG.md
  framework/db/ActiveRelationTrait.php
  tests/data/ar/Order.php
  tests/data/ar/OrderItem.php
  tests/framework/db/ActiveRecordTest.php
Labels: type:bug

#18438 Fix typo in ArrayableTrait.php
  framework/base/ArrayableTrait.php
Labels: type:docs

#18435 Model key normalization
  framework/CHANGELOG.md
  framework/db/ActiveRelationTrait.php
Labels: status:ready for merge, type:bug

#18437 Change order checking in \yii\base\ArrayableTrait::toArray() and \yii\rest\Serializer::serialize()
  .github/workflows/build.yml
  framework/CHANGELOG.md
  framework/base/ArrayableTrait.php
  framework/rest/Serializer.php
  tests/framework/rest/SerializerTest.php
Labels: status:code review, type:docs

#18441 Fix typo in SafeValidator.php
  framework/validators/SafeValidator.php
Labels: type:docs

#18444 Allow filtering arrays with numeric keys
  framework/CHANGELOG.md
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: type:bug

#18442 No array access in strings
  build/controllers/DevController.php
  build/controllers/MimeTypeController.php
  build/controllers/PhpDocController.php
  build/controllers/TranslationController.php
  framework/BaseYii.php
  framework/CHANGELOG.md
  framework/caching/FileCache.php
  framework/console/controllers/MessageController.php
  framework/db/oci/Schema.php
  framework/db/pgsql/Schema.php
  framework/helpers/BaseFileHelper.php
  framework/helpers/BaseUrl.php
  framework/i18n/GettextMessageSource.php
  framework/i18n/MessageFormatter.php
  framework/i18n/PhpMessageSource.php
  framework/widgets/Menu.php
  tests/framework/helpers/FileHelperTest.php
Labels: type:bug

#18445 Moving quoting of table names to upper level (to function getSchemaMetadata)
  framework/CHANGELOG.md
  framework/db/mssql/Schema.php
Labels: MSSQL, status:ready for merge

#18418 trim @web before looking for the asset in webroot, fixes #18414
  framework/CHANGELOG.md
  framework/web/View.php
  tests/framework/web/ViewTest.php
Labels: status:ready for merge, type:bug

#18447 Solution for correct getting PK from insert query without function `getLastInsertID`
  framework/CHANGELOG.md
  framework/db/mssql/Schema.php
  tests/framework/db/mssql/SchemaTest.php
Labels: MSSQL, status:code review

#18448 fixes for Sql Server 2008 and early
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  tests/framework/db/mssql/ActiveRecordTest.php
Labels: MSSQL, status:ready for merge
