Repository yiisoft/yii2, pull requests merged in 2020-10, with the labels that each got.

#18309 Error summary order as in validators
  framework/CHANGELOG.md
  framework/base/Model.php
  tests/framework/base/ModelTest.php
Labels: type:bug

#18290 fix for non-seekable streams
  Dockerfile
  framework/CHANGELOG.md
  framework/web/Response.php
  tests/framework/web/ResponseTest.php
Labels: status:ready for merge, type:bug

#18307 Fix for OUTPUT INSERTED and computed columns
  framework/CHANGELOG.md
  framework/db/mssql/ColumnSchema.php
  framework/db/mssql/QueryBuilder.php
  framework/db/mssql/Schema.php
  tests/framework/db/mssql/ActiveRecordTest.php
  tests/framework/db/mssql/QueryBuilderTest.php
Labels: MSSQL, status:ready for merge, type:bug

#18311 Fix creating migration with defaultValue
  framework/CHANGELOG.md
  framework/console/controllers/MigrateController.php
  tests/data/console/migrate_create/create_fields_with_col_method_after_default_value.php
  tests/framework/console/controllers/MigrateControllerTest.php
Labels: status:ready for merge, type:bug

#18314 Fix multiform data parse with double quotes which fixes #18313
  framework/CHANGELOG.md
  framework/web/MultipartFormDataParser.php
  tests/framework/web/MultipartFormDataParserTest.php
Labels: status:code review

#18319 build: Improved generation for class properties
  build/controllers/PhpDocController.php
Labels: status:ready for merge, type:enhancement

#18320 Correcting a typo in `guide-ru/db-migrations.md`
  docs/guide-ru/db-migrations.md
Labels: type:docs

#18324 typo
  .github/SECURITY.md
Labels: type:docs

#18337 Typo in documentation
  framework/grid/DataColumn.php
Labels: type:docs

#18341 change type of function updateAll in ActiveRecordInterface.php (for p…
  framework/db/ActiveRecordInterface.php
Labels: type:docs

#18343 docs: Improvement for Russian documentation
  docs/guide-ru/caching-data.md
  docs/guide-ru/caching-fragment.md
  docs/guide-ru/caching-http.md
  docs/guide-ru/caching-page.md
  docs/guide-ru/concept-aliases.md
  docs/guide-ru/concept-autoloading.md
  docs/guide-ru/concept-behaviors.md
  docs/guide-ru/concept-configurations.md
  docs/guide-ru/concept-di-container.md
  docs/guide-ru/concept-events.md
  docs/guide-ru/concept-service-locator.md
  docs/guide-ru/db-active-record.md
  docs/guide-ru/db-dao.md
  docs/guide-ru/db-migrations.md
  docs/guide-ru/db-query-builder.md
  docs/guide-ru/glossary.md
  docs/guide-ru/helper-array.md
  docs/guide-ru/helper-html.md
  docs/guide-ru/helper-url.md
  docs/guide-ru/input-form-javascript.md
  docs/guide-ru/input-forms.md
  docs/guide-ru/intro-upgrade-from-v1.md
  docs/guide-ru/intro-yii.md
  docs/guide-ru/rest-error-handling.md
  docs/guide-ru/rest-routing.md
  docs/guide-ru/runtime-logging.md
  docs/guide-ru/runtime-requests.md
  docs/guide-ru/runtime-responses.md
  docs/guide-ru/runtime-routing.md
  docs/guide-ru/security-authorization.md
  docs/guide-ru/start-forms.md
  docs/guide-ru/start-hello.md
  docs/guide-ru/start-workflow.md
  docs/guide-ru/structure-applications.md
  docs/guide-ru/structure-controllers.md
  docs/guide-ru/structure-models.md
  docs/guide-ru/structure-modules.md
  docs/guide-ru/test-environment-setup.md
  docs/guide-ru/test-fixtures.md
  docs/guide-ru/test-overview.md
  docs/guide-ru/tutorial-i18n.md
  docs/guide-ru/tutorial-performance-tuning.md
  docs/guide-ru/tutorial-yii-as-micro-framework.md
Labels: type:docs

#18317 Additional PHP 8 fixes
  .github/workflows/build.yml
  composer.json
  framework/CHANGELOG.md
  framework/base/ErrorException.php
  framework/base/ExitException.php
  framework/console/Controller.php
  framework/db/Command.php
  framework/db/Exception.php
  framework/di/Container.php
  tests/data/validators/models/FakedValidationModel.php
  tests/framework/db/ActiveRecordTest.php
  tests/framework/filters/RateLimiterTest.php
  tests/framework/filters/stubs/ExposedLogger.php
  tests/phpunit_mock_objects.patch
  tests/phpunit_php7.patch
  tests/phpunit_php8.patch
Labels: status:code review

#18322 Fix line break for output in console/widgets/Table.php
  framework/CHANGELOG.md
  framework/console/widgets/Table.php
  framework/helpers/BaseConsole.php
  tests/framework/console/widgets/TableTest.php
  tests/framework/helpers/BaseConsoleTest.php
Labels: type:bug

#18334 feat(cache): Stopped generating constant directory level
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/caching/FileCache.php
  tests/framework/caching/FileCacheTest.php
Labels: status:ready for merge

#18350 Typo fix "Enntêtes HTTP"
  docs/guide-fr/runtime-requests.md
Labels: type:docs

#18348 Update tutorial-core-validators.md
  docs/guide/tutorial-core-validators.md
Labels: status:under discussion

#18247 Respect ini session.use_strict_mode
  .github/workflows/build.yml
  docs/guide/runtime-sessions-cookies.md
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/web/CacheSession.php
  framework/web/DbSession.php
  framework/web/Session.php
  tests/framework/web/session/AbstractDbSessionTest.php
  tests/framework/web/session/CacheSessionTest.php
  tests/framework/web/session/SessionTest.php
  tests/framework/web/session/SessionTestTrait.php
Labels: status:code review

#18358 18351 date validator timestamp timezone
  docs/guide/tutorial-core-validators.md
  framework/CHANGELOG.md
  framework/validators/DateValidator.php
  tests/framework/validators/DateValidatorTest.php
Labels: status:ready for merge

#18285 Add support named parameters for constructor in container.
  docs/guide-ru/concept-di-container.md
  docs/guide/concept-di-container.md
  framework/CHANGELOG.md
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/stubs/Car.php
Labels: status:code review, type:docs
