Repository yiisoft/yii2, pull requests merged in 2020-03, with the labels that each got.

#17904 Fix incorrect assertion in fixture test
  tests/framework/console/controllers/FixtureControllerTest.php
Labels: type:test

#17854 Bug #17679: Fix oracle exception "ORA-01461"
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/Connection.php
  framework/db/oci/Command.php
  tests/framework/db/oci/CommandTest.php
Labels: Oracle, type:bug

#17897 fix: #13749 Yii opens db connection even when hits query cache
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/mysql/QueryBuilder.php
Labels: status:code review

#17900 Fix 16092: Fix duplicate joins in usage of joinWith
  framework/CHANGELOG.md
  framework/db/ActiveQuery.php
  tests/framework/db/ActiveQueryTest.php
  tests/framework/db/ActiveRecordTest.php
Labels: status:code review, type:bug

#17834 Fix for #17797, activeListInput options
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: status:code review, type:bug

#17910 Reset the DB schema, transaction, and driver name on connection close
  framework/CHANGELOG.md
  framework/db/Connection.php
Labels: type:bug

#17920 Fix for `Command::getRawSql`
  framework/CHANGELOG.md
  framework/db/Command.php
  tests/framework/db/CommandTest.php
Labels: status:code review

#17923 Fix MySQL in tests
  .github/workflows/tests.yml
Labels: type:test

#17858 Fix #17667: Fix `CREATE INDEX` failure on sqlite when specifying schema
  framework/CHANGELOG.md
  framework/db/sqlite/QueryBuilder.php
  tests/framework/db/sqlite/QueryBuilderTest.php
Labels: status:code review, type:bug

#17827 Add $strict property and adjust validation
  framework/CHANGELOG.md
  framework/validators/StringValidator.php
  tests/framework/validators/StringValidatorTest.php
Labels: status:code review

#17937 Fix #17932: Fix regression in detection of AJAX requests
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: type:bug

#17938 Fix #17934: Fix regression in Oracle when binding several string parameters
  framework/CHANGELOG.md
  framework/db/oci/Command.php
Labels: type:bug

#17940 #17933: Log warning instead of erroring when URLManager is unable to initialize cache
  framework/CHANGELOG.md
  framework/base/Application.php
  framework/web/UrlManager.php
Labels: status:code review, type:bug
