Repository yiisoft/yii2, pull requests merged in 2020-09, with the labels that each got.

#18265 fix error how try get value by index from int
  framework/CHANGELOG.md
  framework/base/Model.php
  tests/framework/base/ModelTest.php
Labels: status:ready for merge

#18249 Issue #18248 Render only one stack trace for chained exceptions on console
  framework/CHANGELOG.md
  framework/console/ErrorHandler.php
Labels: status:code review

#18230 Pass withQueries parameter when using yii\db\Query::create for query building
  framework/CHANGELOG.md
  framework/db/Query.php
  tests/framework/db/QueryTest.php
Labels: type:bug

#18219 Make fixtures handle circular dependencies (see #18213)
  framework/CHANGELOG.md
  framework/test/FixtureTrait.php
  tests/framework/test/FixtureTest.php
Labels: status:ready for merge, type:enhancement

#18196 DbManager invalidate assignment cache only
  framework/CHANGELOG.md
  framework/rbac/DbManager.php
Labels: status:code review, type:enhancement

#18136 Correct alterColumn for MSSQL & drop constraints before drop column.
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  tests/data/mssql.sql
  tests/framework/db/mssql/QueryBuilderTest.php
Labels: MSSQL, status:code review

#18277 Install codeception as a dev dependency
  docs/guide/test-environment-setup.md
Labels: type:docs

#18225 Add workflow db independent.
  .github/workflows/ci-mysql.yml
  .github/workflows/ci-pgsql.yml
  framework/CHANGELOG.md
  framework/db/pgsql/Schema.php
  tests/framework/db/mysql/SchemaTest.php
  tests/framework/db/pgsql/SchemaTest.php
Labels: status:under development

#18279 Fix testGetColumType Pgsql.
  tests/framework/db/QueryBuilderTest.php
Labels: type:test

#18077 Fix for issue #16892
  framework/CHANGELOG.md
  framework/widgets/ActiveField.php
  tests/framework/widgets/ActiveFormTest.php
Labels: status:code review

#18286 Ensure ActiveQuery is using DB connection set by model
  tests/framework/db/ActiveQueryModelConnectionTest.php
Labels: status:code review, type:test

#18292 16418 pagination links
  framework/CHANGELOG.md
  framework/data/Pagination.php
  tests/framework/data/PaginationTest.php
Labels: status:code review, type:bug, type:test

#18295 Update phpdoc for widget->getId
  framework/base/Widget.php
Labels: type:docs

#18296 Updated phpdoc return type for getExceptionName
  framework/web/ErrorHandler.php
Labels: type:docs

#18302 Updates to ErrorHandler, add missing type hint \Throwable
  framework/base/ErrorHandler.php
  framework/web/Response.php
Labels: type:docs

#18310 document cocept properties chapter yii\base\Object should be yii\base\BaseObject
  docs/guide-zh-CN/concept-properties.md
Labels: type:docs
