Repository yiisoft/yii2, pull requests merged in 2020-02, with the labels that each got.

#17828 Fix yii\web\UploadedFile::saveAs() failing when error value in $_FILES entry is a string
  framework/CHANGELOG.md
  framework/web/UploadedFile.php
  tests/framework/web/UploadedFileTest.php
Labels: status:code review, type:bug

#17847 Issue 17843
  framework/CHANGELOG.md
  framework/web/Session.php
Labels: type:bug

#17848 Fix #7622: Allow `yii\data\ArrayDataProvider` to control the sort flags
  framework/CHANGELOG.md
  framework/data/ArrayDataProvider.php
  framework/data/Sort.php
  tests/framework/data/ArrayDataProviderTest.php
Labels: status:code review, type:enhancement

#17850 Update to InvalidConfigException message
  framework/CHANGELOG.md
  framework/helpers/ReplaceArrayValue.php
Labels: status:ready for merge, type:bug

#17857 Update guide-ru
  docs/guide-ru/helper-html.md
Labels: type:docs

#17860 add detail transport properties in tutorial mailing
  docs/guide/tutorial-mailing.md
Labels: type:docs

#17798 Fix LogTarget to avoid creating folder
  framework/CHANGELOG.md
  framework/log/FileTarget.php
Labels: status:ready for merge, type:bug

#17871 Fix #17863: `\yii\helpers\BaseInflector::slug()` doesn't work with an…
  framework/CHANGELOG.md
  framework/helpers/BaseInflector.php
  tests/framework/helpers/InflectorTest.php
Labels: status:code review

#17876 Execute FormatterDate intl test to PHP 5.5+ only
  tests/framework/i18n/FormatterDateTest.php
Labels: type:test

#17879 Don't tests DATE_ATOM with PHP 5.5
  tests/framework/i18n/FormatterDateTest.php
Labels: type:test

#17877 Revert `move_uploaded_file()` function for saving uploaded files when POST request
  framework/CHANGELOG.md
  framework/web/UploadedFile.php
  tests/framework/web/UploadedFileTest.php
  tests/framework/web/mocks/UploadedFileMock.php
Labels: status:code review

#17881 queryScalar() fix
  framework/CHANGELOG.md
  framework/db/Query.php
Labels: type:bug

#17883 Fix #16334: Serializer support \JsonSerializable
  framework/CHANGELOG.md
  framework/rest/Serializer.php
  tests/framework/rest/SerializerTest.php
Labels: type:bug

#17885 Issue #17884 Fix 0 values in console table
  framework/CHANGELOG.md
  framework/console/widgets/Table.php
  tests/framework/console/widgets/TableTest.php
Labels: type:bug

#17867 WIP: Schema builder mysql [fix #11945]
  framework/CHANGELOG.md
  framework/db/mysql/ColumnSchemaBuilder.php
  tests/framework/db/mysql/ColumnSchemaBuilderTest.php
Labels: status:code review

#17859 Fix fixtures loading under Windows
  framework/CHANGELOG.md
  framework/console/controllers/FixtureController.php
Labels: type:bug
