Repository yiisoft/yii2, pull requests merged in 2020-01, with the labels that each got.

#17779 docs/guide-ja updated [ci skip]
  docs/guide-ja/concept-di-container.md
  docs/guide-ja/db-dao.md
  docs/guide-ja/helper-html.md
  docs/guide-ja/rest-quick-start.md
  docs/guide-ja/runtime-requests.md
  docs/guide-ja/start-looking-ahead.md
Labels: type:docs

#17770 Fix #17767: Make `Formatter::formatNumber` method protected
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
Labels: type:bug

#17781 Fix #17771: migrate/fresh was not returning exit code
  framework/CHANGELOG.md
  framework/console/controllers/BaseMigrateController.php
Labels: status:code review

#17790 Fix #17760: Fix `JSON::encode()` for `\DateTimeInterface` under PHP 7.4
  framework/CHANGELOG.md
  framework/helpers/BaseJson.php
  tests/framework/helpers/JsonTest.php
Labels: status:code review, type:bug

#17789 Fix #12539: `yii\filters\ContentNegotiator` now generates 406 'Not Acceptable' instead of 415 'Unsupported Media Type' on content-type negotiation fail
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/filters/ContentNegotiator.php
  tests/framework/filters/ContentNegotiatorTest.php
Labels: feature:rest, status:code review, type:bug

#17748 Update start-database.md : actionIndex Explanation
  docs/guide/start-databases.md
Labels: type:docs

#17792 Support aria-* attributes like data-* attributes
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:enhancement

#17794 Handle null data values consistently in Html::renderTagAttributes()
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: status:code review, type:bug

#17796 Fix #17766: Remove previous PJAX event binding before registering new one
  framework/CHANGELOG.md
  framework/widgets/Pjax.php
Labels: type:bug

#17729 Fix file uploads saving in case generated by `MultipartFormDataParser`
  framework/CHANGELOG.md
  framework/web/MultipartFormDataParser.php
  framework/web/UploadedFile.php
  tests/framework/web/UploadedFileTest.php
  tests/framework/web/mocks/UploadedFileMock.php
Labels: status:ready for merge, type:bug

#17756 Fix class-level Event handling with wildcards
  framework/CHANGELOG.md
  framework/base/Event.php
  tests/framework/base/EventTest.php
Labels: status:ready for merge

#17774 fix #17755 web request
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: status:code review

#17735 17653 unserialize rbac rule
  docs/guide/db-dao.md
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
Labels: MSSQL, status:code review, type:bug, type:docs

#17821 Rectifying wrong instruction
  docs/guide/start-installation.md
Labels: type:docs

#17830 Arrayhelper filter support more than 2 levels
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: type:bug

#17837 Skip NumberFormatter::asScientific() intl test
  tests/framework/i18n/FormatterNumberTest.php
Labels: type:test

#17822 Created GitHub "tests" action
  .github/workflows/tests.yml
  .gitignore
  .travis.yml.bak
Labels: status:code review
