Repository yiisoft/yii2, pull requests merged in 2020-06, with the labels that each got.

#18076 resolves issue #17852
  framework/console/Controller.php
Labels: type:docs

#18079 Added NGINX Unit config to start-installation.md
  docs/guide/start-installation.md
Labels: type:docs

#18081 Fix for PDO_DBLIB (MSSQL).
  framework/CHANGELOG.md
  framework/db/Connection.php
Labels: MSSQL, type:bug

#18085 Fix for issue #13828: Get Primary Key Uniqueidentifier Yii 2.0.11
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  framework/db/mssql/Schema.php
Labels: MSSQL

#18088 Brackets checking removed from the return condition.
  framework/CHANGELOG.md
  framework/db/Schema.php
  tests/framework/db/ConnectionTest.php
Labels: type:bug

#18095 docs/guide-ja updated [ci skip]
  docs/guide-ja/db-dao.md
  docs/guide-ja/db-query-builder.md
  docs/guide-ja/start-databases.md
  docs/guide-ja/start-hello.md
  docs/guide-ja/start-installation.md
  docs/guide-ja/tutorial-mailing.md
Labels: type:docs

#18032 Fixes #17722
  docs/guide/concept-di-container.md
  framework/CHANGELOG.md
  framework/base/Controller.php
  framework/console/Controller.php
  framework/web/Controller.php
  tests/framework/console/ControllerTest.php
  tests/framework/console/FakePhp71Controller.php
  tests/framework/console/stubs/DummyService.php
  tests/framework/web/ControllerTest.php
  tests/framework/web/FakePhp71Controller.php
Labels: status:code review, type:enhancement

#18102 master/slave → primary/replica
  docs/guide-es/db-dao.md
  docs/guide-fr/db-dao.md
  docs/guide-ja/db-dao.md
  docs/guide-ru/db-dao.md
  docs/guide-zh-CN/db-dao.md
  docs/guide/db-dao.md
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/Connection.php
  framework/db/ConnectionDeprecationsTrait.php
  framework/db/Migration.php
  framework/db/Schema.php
  framework/db/cubrid/Schema.php
  framework/db/mysql/QueryBuilder.php
  framework/db/mysql/Schema.php
  framework/db/oci/QueryBuilder.php
  framework/db/oci/Schema.php
  framework/db/pgsql/QueryBuilder.php
  framework/db/pgsql/Schema.php
  framework/db/sqlite/QueryBuilder.php
  framework/mutex/MysqlMutex.php
  framework/mutex/OracleMutex.php
  framework/mutex/PgsqlMutex.php
  framework/validators/ExistValidator.php
  framework/validators/ForceMasterDbTrait.php
  framework/validators/UniqueValidator.php
  framework/web/DbSession.php
  tests/framework/db/CommandTest.php
  tests/framework/db/ConnectionTest.php
  tests/framework/db/DatabaseTestCase.php
  tests/framework/db/SchemaTest.php
  tests/framework/db/cubrid/QueryBuilderTest.php
  tests/framework/db/mysql/QueryBuilderTest.php
  tests/framework/db/sqlite/ConnectionTest.php
  tests/framework/helpers/VarDumperTest.php
  tests/framework/validators/ExistValidatorTest.php
  tests/framework/validators/UniqueValidatorTest.php
Labels: status:code review

#18101 Mssql fix and tests
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  tests/framework/db/mssql/QueryBuilderTest.php
  tests/framework/web/session/AbstractDbSessionTest.php
Labels: MSSQL

#18083 Controller::$request and $response
  framework/CHANGELOG.md
  framework/base/Controller.php
  framework/console/Controller.php
  framework/web/Controller.php
  tests/framework/console/controllers/CacheControllerTest.php
  tests/framework/web/ControllerTest.php
Labels: status:code review

#18104 blacklist → exclude
  docs/guide/rest-resources.md
  docs/guide/runtime-logging.md
  docs/guide/structure-filters.md
  docs/guide/structure-models.md
Labels: type:docs

#18097 Fix #18096: Fix InlineValidator with anonymous inline function not wo…
  framework/CHANGELOG.md
  framework/validators/InlineValidator.php
  tests/data/validators/models/ValidatorTestEachAndInlineMethodModel.php
  tests/framework/validators/EachValidatorTest.php
Labels: type:bug

#18105 Table prefix fix
  framework/CHANGELOG.md
  framework/rbac/migrations/m200409_110543_rbac_update_mssql_trigger.php
Labels: type:bug

#18106 master/slave → primary/replica (take 2)
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/Connection.php
  framework/db/ConnectionDeprecationsTrait.php
  framework/db/Migration.php
  framework/db/Schema.php
  framework/db/cubrid/Schema.php
  framework/db/mysql/QueryBuilder.php
  framework/db/mysql/Schema.php
  framework/db/oci/QueryBuilder.php
  framework/db/oci/Schema.php
  framework/db/pgsql/QueryBuilder.php
  framework/db/sqlite/QueryBuilder.php
  framework/mutex/MysqlMutex.php
  framework/mutex/OracleMutex.php
  framework/mutex/PgsqlMutex.php
  framework/validators/ExistValidator.php
  framework/validators/ForceMasterDbTrait.php
  framework/validators/UniqueValidator.php
  framework/web/DbSession.php
  tests/framework/db/ConnectionTest.php
  tests/framework/db/SchemaTest.php
  tests/framework/db/cubrid/QueryBuilderTest.php
  tests/framework/db/mysql/QueryBuilderTest.php
  tests/framework/db/sqlite/ConnectionTest.php
  tests/framework/validators/ExistValidatorTest.php
  tests/framework/validators/UniqueValidatorTest.php
Labels: status:code review

#18112 Adding some important hints for IIS Configuration
  docs/guide/start-installation.md
Labels: type:docs

#18120 Add path to the failed log file
  framework/CHANGELOG.md
  framework/log/FileTarget.php
Labels: type:enhancement

#18123 fix for PR#18105
  framework/rbac/migrations/m200409_110543_rbac_update_mssql_trigger.php
Labels: MSSQL

#18128 small fix for issue #18110
  framework/CHANGELOG.md
  framework/db/mssql/Schema.php
Labels: MSSQL, status:code review

#18117 Allow to load services from module's container
  framework/CHANGELOG.md
  framework/base/Controller.php
  tests/framework/console/ControllerTest.php
  tests/framework/console/FakePhp71Controller.php
  tests/framework/web/ControllerTest.php
  tests/framework/web/FakePhp71Controller.php
Labels: type:bug

#18122 Add optional param `--silent-exit-on-exception` in `yii\console\Controller`
  framework/CHANGELOG.md
  framework/base/ErrorHandler.php
  framework/console/Controller.php
  tests/framework/console/controllers/HelpControllerTest.php
Labels: status:code review, type:enhancement

#18121 Fix #18047: Console Table Widget width issue with colorized input
  framework/CHANGELOG.md
  framework/console/widgets/Table.php
  framework/helpers/BaseConsole.php
  tests/framework/console/widgets/TableTest.php
Labels: status:code review, type:bug

#18127 Allow DI references in array in dependencies
  framework/CHANGELOG.md
  framework/di/Container.php
  tests/framework/di/ContainerTest.php
  tests/framework/di/stubs/Corge.php
Labels: status:ready for merge, type:bug

#18138 removed redundant line
  docs/guide-pl/start-forms.md
Labels: type:docs

#18142 Db expression
  framework/CHANGELOG.md
  framework/db/Connection.php
  tests/framework/db/QueryBuilderTest.php
Labels: type:bug

#18009 Fix skipping test case on PHP v >= 7.1 and LibreSSL version >= 2.15 #17999
  framework/base/Security.php
  tests/framework/base/ExposedSecurity.php
  tests/framework/base/SecurityTest.php
Labels: status:code review
