Repository yiisoft/yii2, pull requests merged in 2020-08, with the labels that each got.

#18193 Add test for 18031 - User login events not triggered when using \yii\web\HttpBasicAuth login
  tests/framework/filters/auth/BasicAuthTest.php
Labels: status:code review, type:test

#18205 Added .phpstorm.meta.php for DI container.
  framework/.phpstorm.meta.php
  framework/CHANGELOG.md
Labels: type:enhancement

#18212 Fix #18204: Fix 2.0.36 regression in inline validator and JS validation
  framework/CHANGELOG.md
  framework/validators/InlineValidator.php
Labels: type:bug

#18065 Fix #17147: Correct form validations for empty select (fixes #16253)
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
Labels: JS, help wanted, pr:request for unit tests, status:code review

#18214 Fix for tables with trigger - output inserted data from insert query with usage temporary table
  framework/CHANGELOG.md
  framework/db/mssql/QueryBuilder.php
  tests/data/ar/TestTrigger.php
  tests/data/ar/TestTriggerAlert.php
  tests/data/mssql.sql
  tests/framework/db/mssql/ActiveRecordTest.php
  tests/framework/db/mssql/QueryBuilderTest.php
Labels: MSSQL, type:bug

#18215 Fix 18210
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#18216 Fix #18203: PDO exception code was not properly passed to `yii\db\Exception`
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/db/Exception.php
  framework/db/Schema.php
Labels: type:bug

#18156 Fixed Typo tableQuoteCharacter vs columnQuoteCharacter
  framework/CHANGELOG.md
  framework/db/Schema.php
Labels: pr:request for unit tests, status:code review, type:bug

#18218 Issue #18217 Render chained exceptions in console ErrorHandler
  framework/CHANGELOG.md
  framework/console/ErrorHandler.php
Labels: status:code review, type:enhancement

#18233 Add PHP 8 support
  .github/workflows/build.yml
  framework/CHANGELOG.md
  framework/di/Container.php
Labels: type:bug

#18234 docs/guide-ja updated [ci skip]
  docs/guide-ja/concept-di-container.md
  docs/guide-ja/input-validation.md
  docs/guide-ja/rest-resources.md
  docs/guide-ja/runtime-logging.md
Labels: type:docs

#18237 docs/guide-ja updates
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/start-installation.md
  docs/guide-ja/tutorial-performance-tuning.md
Labels: type:docs

#18231 Add flag for recognize SyBase databases on uses pdo_dblib
  framework/CHANGELOG.md
  framework/db/Connection.php
Labels: status:ready for merge, type:enhancement

#18243 Update structure-assets.md
  docs/guide-ru/structure-assets.md
Labels: type:docs

#18238 allow rate limiter to work with user closure
  framework/CHANGELOG.md
  framework/filters/RateLimiter.php
  tests/framework/filters/RateLimiterTest.php
Labels: status:code review

#18242 Fix support of no-extension files for FileValidator::validateExtension
  framework/CHANGELOG.md
  framework/assets/yii.validation.js
  framework/validators/FileValidator.php
  tests/framework/validators/FileValidatorTest.php
Labels: status:code review, type:bug

#18261 added docs about IP blocks for property $ips
  framework/filters/AccessRule.php
Labels: type:docs
