Repository yiisoft/yii2, pull requests merged in 2020-04, with the labels that each got.

#17949 Fix for #17942
  framework/CHANGELOG.md
  framework/db/mysql/QueryBuilder.php
Labels: status:code review

#17945 Update the translating
  docs/guide-ru/security-authorization.md
Labels: type:docs

#17944 Fix #17810 EachValidator crashing with uninitialized typed properties
  framework/CHANGELOG.md
  framework/base/DynamicModel.php
  framework/validators/EachValidator.php
  tests/data/validators/models/FakedValidationModel.php
  tests/data/validators/models/ValidatorTestTypedPropModel.php
  tests/framework/validators/EachValidatorTest.php
Labels: php7, type:bug

#17948 Ignore set_time_limit() errors
  framework/CHANGELOG.md
  framework/web/Response.php
Labels: type:bug

#17967 Document [alias=>table] syntax for join methods
  framework/db/Query.php
Labels: type:docs

#17962 Fix unsigned primary key type mapping for SQLite
  framework/CHANGELOG.md
  framework/db/sqlite/QueryBuilder.php
  tests/README.md
  tests/framework/db/QueryBuilderTest.php
Labels: status:code review

#17758 Feature: New SQL syntax WITH for Query and QueryBuilder
  docs/guide/db-query-builder.md
  framework/CHANGELOG.md
  framework/db/Query.php
  framework/db/QueryBuilder.php
  framework/db/sqlite/QueryBuilder.php
  tests/framework/db/QueryBuilderTest.php
  tests/framework/db/sqlite/QueryBuilderTest.php
Labels: status:code review, type:enhancement

#17974 fix #17914 ActiveRelationTrait compatibility with php 7.4
  framework/CHANGELOG.md
  framework/db/ActiveRelationTrait.php
Labels: php7, status:code review

#17998 Missin third parameter in function preg_match. Test was skipped.
  tests/framework/ChangeLogTest.php
Labels: type:test

#17653 fix TypeError: pair[1] is undefined when query param doesn't have = sign
  framework/CHANGELOG.md
  framework/assets/yii.js
  tests/js/tests/yii.test.js
Labels: JS, status:code review, status:to be verified
