Repository yiisoft/yii2, pull requests merged in 2020-05, with the labels that each got.

#18013 Allow SameSite cookie prior to PHP 7.3 #18006
  framework/CHANGELOG.md
  framework/web/Response.php
  framework/web/Session.php
  tests/framework/web/ResponseTest.php
Labels: status:code review, type:enhancement

#18012 fixed validation of \yii\base\DynamicModel class by adding attribute labels
  framework/CHANGELOG.md
  framework/base/DynamicModel.php
  framework/validators/EachValidator.php
  tests/framework/validators/EachValidatorTest.php
Labels: status:code review, type:bug

#18005 Fixes #18000 PK value of AR is missing after save
  framework/CHANGELOG.md
  framework/db/oci/Schema.php
  tests/data/ar/DefaultMultiplePk.php
  tests/data/oci.sql
  tests/framework/db/oci/ActiveRecordTest.php
Labels: Oracle, status:code review, type:bug

#17997 17993 currency decimal separator
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
  tests/framework/i18n/FormatterNumberTest.php
Labels: status:code review, type:enhancement

#17992 Improve `yii\db\Connection` master and slave failover
  framework/CHANGELOG.md
  framework/db/Connection.php
Labels: status:code review

#17968 Bug #17961: Fix pagination `pageSizeLimit` ignore if set as array with more then 2 elements
  framework/CHANGELOG.md
  framework/data/Pagination.php
Labels: status:code review

#17966 split original trigger into two distinct ones.
  framework/CHANGELOG.md
  framework/rbac/migrations/m200409_110543_rbac_update_mssql_trigger.php
Labels: MSSQL, status:code review, type:bug

#18021 Fix deleting unused message
  framework/CHANGELOG.md
  framework/i18n/migrations/schema-mssql.sql
  framework/i18n/migrations/schema-mysql.sql
  framework/i18n/migrations/schema-pgsql.sql
  framework/i18n/migrations/schema-sqlite.sql
Labels: type:bug

#18029 Added links to "testing" guide for templates in documentation
  docs/guide-ru/test-unit.md
Labels: type:docs

#18028 Fix division by zero exception in Table.php::calculateRowHeight
  framework/CHANGELOG.md
  framework/console/widgets/Table.php
  tests/framework/console/widgets/TableTest.php
Labels: status:ready for merge, type:bug

#18027 add ArrayAccess support for BaseArrayHelper
  framework/CHANGELOG.md
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: status:code review, type:bug

#18048 Updating setting parameter User::$accessChecker
  framework/CHANGELOG.md
  framework/web/User.php
  tests/framework/web/UserTest.php
Labels: status:code review

#18054 Fix #18046: Add test for current ArrayHelper::merge() behavior
  tests/framework/helpers/ArrayHelperTest.php
Labels: type:test

#18052 Adding support for custom rule in EachValidator
  framework/CHANGELOG.md
  framework/validators/Validator.php
  tests/data/base/Speaker.php
  tests/framework/validators/EachValidatorTest.php
  tests/framework/validators/ValidatorTest.php
Labels: status:ready for merge
