Repository yiisoft/yii2, pull requests merged in 2021-01, with the labels that each got.

#18473 Fix initializing db component configuration in ActiveDataProvider
  framework/CHANGELOG.md
  framework/data/ActiveDataProvider.php
Labels: status:code review, type:bug

#18466 Missing upgrade info
  framework/CHANGELOG.md
  framework/UPGRADE.md
Labels: type:docs

#18457 BatchQueryResult reset/finish events
  framework/CHANGELOG.md
  framework/db/BatchQueryResult.php
Labels: feature:db, type:enhancement

#18462 [doc] More examples and explanation for `exists` and `unique` core validators
  docs/guide/tutorial-core-validators.md
Labels: type:docs

#18475 Fix initializing db component configuration
  framework/data/ActiveDataProvider.php
  tests/framework/data/ActiveDataProviderCloningTest.php
  tests/framework/data/ActiveDataProviderTest.php
  tests/framework/widgets/LinkSorterTest.php
Labels: type:bug

#18465 Fix bug with processing fallback messages
  framework/CHANGELOG.md
  framework/i18n/GettextMessageSource.php
  framework/i18n/PhpMessageSource.php
  tests/framework/i18n/I18NTest.php
Labels: type:bug

#18463 Update public property types of `yii\base\Module`
  framework/base/Module.php
Labels: type:docs

#18478 Fix typo in Connection.php
  framework/db/Connection.php
Labels: type:docs

#18476 Correct conditional configuration of db property
  framework/data/ActiveDataProvider.php
  tests/framework/data/ActiveDataProviderCloningTest.php
  tests/framework/data/ActiveDataProviderTest.php
  tests/framework/widgets/LinkSorterTest.php
Labels: type:bug

#18455 Ability to use separate attributes for data model and filter model of `yii\grid\GridView` in `yii\grid\DataColumn`
  framework/CHANGELOG.md
  framework/grid/DataColumn.php
  tests/framework/grid/DataColumnTest.php
Labels: status:code review, type:enhancement

#18482 Fix detecting availability of Xdebug's stack trace
  framework/CHANGELOG.md
  framework/base/ErrorException.php
  tests/framework/base/ErrorExceptionTest.php
Labels: type:bug

#18481 Use separate driver for DBLib connections due to transaction issues
  framework/CHANGELOG.md
  framework/db/Connection.php
  framework/db/mssql/DBLibPDO.php
Labels: type:bug

#18479 Fix console\Controller preg_split error
  framework/CHANGELOG.md
  framework/console/Controller.php
  tests/framework/console/ControllerTest.php
Labels: status:code review, type:bug

#18484 Enh #18483: Add property `yii\log\Logger::dbEventNames` - an array wi…
  framework/CHANGELOG.md
  framework/log/Logger.php
Labels: type:enhancement

#18495 Allowing non-GET-verb URL rules to have a URL created
  framework/CHANGELOG.md
  framework/rest/UrlRule.php
  framework/web/UrlManager.php
  tests/framework/rest/UrlRuleTest.php
  tests/framework/web/UrlManagerCreateUrlTest.php
  tests/framework/web/UrlManagerParseUrlTest.php
Labels: status:code review

#18493 Handling prefix in REST UrlRule when parsing request
  framework/CHANGELOG.md
  framework/rest/UrlRule.php
  tests/framework/rest/UrlRuleTest.php
Labels: status:code review

#18500 Support for MySQL ANSI/ANSI_QUOTES modes
  framework/CHANGELOG.md
  framework/db/mysql/QueryBuilder.php
  framework/db/mysql/Schema.php
Labels: status:ready for merge, type:enhancement
