Repository yiisoft/yii2, pull requests merged in 2021-09, with the labels that each got.

#18862 Cache: use defaultDuration for multiSet when no duration is provided
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/caching/Cache.php
  framework/caching/CacheInterface.php
Labels: type:bug

#18845 `MigrateController::addDefaultPrimaryKey()` skip if 'id' already set
  framework/CHANGELOG.md
  framework/console/controllers/MigrateController.php
  tests/data/console/migrate_create/create_id_field_not_as_pk.php
  tests/framework/console/controllers/MigrateControllerTest.php
Labels: type:bug

#18864 update PHP callback link
  docs/guide-fr/concept-events.md
  docs/guide-pt-BR/concept-events.md
  docs/guide-zh-CN/concept-events.md
  docs/guide/concept-events.md
Labels: type:docs

#18812 Update errors in Json helper
  framework/CHANGELOG.md
  framework/helpers/BaseJson.php
Labels: status:code review

#18869 Fix bindInjectedParams for PHP8 ReflectionUnionType
  framework/CHANGELOG.md
  framework/base/Controller.php
  framework/console/Controller.php
  framework/web/Controller.php
Labels: type:bug, php8

#18874 update class autoloading mechanism link
  docs/guide-fr/concept-autoloading.md
  docs/guide-pt-BR/concept-autoloading.md
  docs/guide-zh-CN/concept-autoloading.md
  docs/guide/concept-autoloading.md
Labels: type:docs

#18881 update namespace links
  docs/guide-ar/start-prerequisites.md
  docs/guide-fr/concept-autoloading.md
  docs/guide-id/intro-upgrade-from-v1.md
  docs/guide-id/intro-yii.md
  docs/guide-it/intro-upgrade-from-v1.md
  docs/guide-pt-BR/concept-autoloading.md
  docs/guide-pt-BR/intro-yii.md
  docs/guide-ru/glossary.md
  docs/guide-tr/intro-yii.md
  docs/guide-tr/start-prerequisites.md
  docs/guide-uk/concept-autoloading.md
  docs/guide-uk/intro-upgrade-from-v1.md
  docs/guide-uk/intro-yii.md
  docs/guide-vi/intro-yii.md
  docs/guide-vi/start-prerequisites.md
  docs/guide-zh-CN/intro-yii.md
  docs/guide-zh-CN/start-prerequisites.md
  docs/guide/concept-autoloading.md
  docs/guide/glossary.md
  docs/guide/intro-upgrade-from-v1.md
  docs/guide/intro-yii.md
  docs/guide/start-prerequisites.md
Labels: type:docs

#18883 Fix header collection from array
  framework/CHANGELOG.md
  framework/web/HeaderCollection.php
  tests/framework/web/HeaderCollectionTest.php
Labels: type:bug

#18889 update PDO link
  docs/guide-ar/start-databases.md
  docs/guide-fr/db-dao.md
  docs/guide-id/start-databases.md
  docs/guide-ja/start-databases.md
  docs/guide-pl/start-databases.md
  docs/guide-pt-BR/start-databases.md
  docs/guide-uk/start-databases.md
  docs/guide-vi/start-databases.md
  docs/guide-zh-CN/start-databases.md
  docs/guide/db-dao.md
  docs/guide/start-databases.md
Labels: type:docs

#18896 update oracle link
  docs/guide-es/db-dao.md
  docs/guide-fr/db-dao.md
  docs/guide-ja/db-dao.md
  docs/guide-ru/db-dao.md
  docs/guide-zh-CN/db-dao.md
  docs/guide/db-dao.md
Labels: type:docs

#18900 Fix mb_ucwords when a word ends with 0
  framework/CHANGELOG.md
  framework/helpers/BaseStringHelper.php
  tests/framework/helpers/StringHelperTest.php
Labels: type:bug

#18905 update PHP manual link
  docs/guide-fr/db-dao.md
  docs/guide-zh-CN/db-dao.md
  docs/guide/db-dao.md
Labels: type:docs

#18906 enh #18904: Improve Captcha client-side validation
  framework/CHANGELOG.md
  framework/assets/yii.validation.js
  framework/captcha/CaptchaAction.php
  tests/js/tests/yii.validation.test.js
Labels: type:enhancement, status:code review

#18899 Fix misused array_merge, array_values misused, constant time string comparsion via strncmp
  framework/BaseYii.php
  framework/CHANGELOG.md
  framework/caching/FileCache.php
  framework/console/controllers/MessageController.php
  framework/console/controllers/MigrateController.php
  framework/data/ActiveDataFilter.php
  framework/db/Schema.php
  framework/db/oci/Schema.php
  framework/db/pgsql/Schema.php
  framework/helpers/BaseArrayHelper.php
  framework/helpers/BaseFileHelper.php
  framework/helpers/BaseUrl.php
  framework/i18n/MessageFormatter.php
  framework/log/Logger.php
  framework/rest/CreateAction.php
  framework/validators/UniqueValidator.php
  framework/widgets/Menu.php
Labels: status:ready for merge

#18911 update prepared statements link
  docs/guide-fr/db-dao.md
  docs/guide-zh-CN/db-dao.md
  docs/guide/db-dao.md
Labels: type:docs

#18913 MessageSource::getMessageFilePath() - filename injection
  framework/CHANGELOG.md
  framework/i18n/GettextMessageSource.php
  framework/i18n/PhpMessageSource.php
Labels: severity:security, status:ready for merge
