Repository yiisoft/yii2, pull requests merged in 2021-03, with the labels that each got.

#18527 Corrected #18499
  framework/db/Query.php
  tests/framework/db/ActiveRecordTest.php
Labels: type:bug

#18537 Allow empty string to be passed as a nullable typed argument
  framework/CHANGELOG.md
  framework/web/Controller.php
  tests/framework/web/ControllerTest.php
  tests/framework/web/FakePhp7Controller.php
Labels: type:bug

#18539 Bug 18538. fix "driver does not support quoting" when using the drive…
  framework/CHANGELOG.md
  framework/db/Schema.php
Labels: type:bug

#18541 Fix #18535: Set Cookie SameSite to Lax by default
  framework/CHANGELOG.md
  framework/web/Cookie.php
Labels: status:code review

#18540 Fix #9718: Fix user staying authorized despite authKey change
  docs/guide/security-authentication.md
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/web/IdentityInterface.php
  framework/web/User.php
  tests/framework/filters/stubs/UserIdentity.php
  tests/framework/web/UserTest.php
Labels: status:code review, type:bug

#18546 Reversed #18499
  docs/guide/db-query-builder.md
  framework/CHANGELOG.md
  framework/db/ActiveQueryInterface.php
  framework/db/Query.php
  framework/db/QueryInterface.php
  framework/db/QueryTrait.php
  tests/framework/db/ActiveRecordTest.php
  tests/framework/db/QueryTest.php
Labels: type:bug

#18550 Fix parsing rest rule
  framework/CHANGELOG.md
  framework/rest/UrlRule.php
  tests/framework/rest/UrlRuleTest.php
Labels: type:bug

#18555 Update OWASP link
  framework/web/Cookie.php
Labels: type:docs

#18553 Allow identifier marks in ORDER BY clause pattern in SqlDataProvider
  framework/CHANGELOG.md
  framework/data/SqlDataProvider.php
  tests/framework/data/SqlDataProviderTest.php
Labels: status:code review, type:bug

#18554 No white spaces for NumberValidator
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/validators/NumberValidator.php
  tests/framework/validators/NumberValidatorTest.php
Labels: status:code review, type:bug

#18561 Fixed types
  framework/base/Model.php
  framework/data/Pagination.php
  framework/db/Connection.php
  framework/db/TableSchema.php
  framework/helpers/BaseFileHelper.php
  framework/rbac/BaseManager.php
  framework/web/CookieCollection.php
  framework/web/HeaderCollection.php
Labels: type:docs

#18559 fixed #17479
  framework/CHANGELOG.md
  framework/grid/ActionColumn.php
  tests/framework/grid/ActionColumnTest.php
Labels: type:bug

#18534 prepareSearchQuery callable function
  framework/CHANGELOG.md
  framework/rest/IndexAction.php
  tests/framework/rest/IndexActionTest.php
Labels: status:code review, type:enhancement

#18560 Connection class for ActiveDataProvider
  framework/CHANGELOG.md
  framework/data/ActiveDataProvider.php
Labels: type:bug

#18564 Fix unlink with onCondition
  framework/CHANGELOG.md
  framework/db/BaseActiveRecord.php
  tests/data/ar/Order.php
  tests/data/cubrid.sql
  tests/data/mssql.sql
  tests/data/mysql.sql
  tests/data/oci.sql
  tests/data/postgres.sql
  tests/data/sqlite.sql
  tests/framework/ar/ActiveRecordTestTrait.php
  tests/framework/db/ActiveRecordTest.php
  tests/framework/db/pgsql/ActiveRecordTest.php
Labels: type:bug

#18571 #17479 icon size fix (inline styles)
  framework/grid/ActionColumn.php
  tests/framework/grid/ActionColumnTest.php
Labels: type:bug

#18575 Use the correct db if strict mode is used in DbSession fixes #18574
  framework/CHANGELOG.md
  framework/web/DbSession.php
Labels: type:bug

#18577 Active fixture model db connection
  framework/CHANGELOG.md
  framework/test/ActiveFixture.php
  tests/framework/console/controllers/FixtureControllerTest.php
  tests/framework/test/ActiveFixtureTest.php
Labels: status:code review, type:bug

#18573 Minified SVGs
  framework/grid/ActionColumn.php
  tests/framework/grid/ActionColumnTest.php
Labels: type:enhancement

#18570 Throw the original exception when bindInjectedParams catches HttpExce…
  framework/CHANGELOG.md
  framework/web/Controller.php
  tests/framework/web/ControllerTest.php
  tests/framework/web/FakePhp71Controller.php
  tests/framework/web/stubs/ModelBindingStub.php
Labels: status:code review, type:enhancement

#18580 Custom summary rendering in ListView
  framework/CHANGELOG.md
  framework/widgets/BaseListView.php
  tests/framework/widgets/ListViewTest.php
Labels: status:code review, type:bug

#18325 pgsql: fix non-standart schema (public ) for column types
  framework/CHANGELOG.md
  framework/db/pgsql/Schema.php
  tests/data/ar/EnumTypeInCustomSchema.php
  tests/data/postgres.sql
  tests/framework/db/pgsql/SchemaTest.php
Labels: PostgreSQL, feature:db, type:bug
