Repository yiisoft/yii2, pull requests merged in 2021-04, with the labels that each got.

#18592 Db Pgsql getRawSql params replace fix
  framework/CHANGELOG.md
  framework/db/Command.php
  tests/framework/db/CommandTest.php
  tests/framework/db/pgsql/CommandTest.php
Labels: type:bug

#18596 Fixed typo in console/Application.php
  framework/console/Application.php
Labels: type:docs

#18598 Clean Oracle workflow
  .github/workflows/ci-oracle.yml
Labels: type:test

#18588 Fixing Email Validator to handle edge case
  framework/CHANGELOG.md
  framework/validators/EmailValidator.php
  tests/framework/validators/EmailValidatorTest.php
Labels: status:ready for merge

#18593 Fix issue 18591
  framework/CHANGELOG.md
  framework/helpers/BaseHtml.php
  tests/framework/helpers/HtmlTest.php
Labels: type:bug

#18597 UrlManager with lazy cache initiating
  framework/CHANGELOG.md
  framework/web/UrlManager.php
  tests/framework/web/UrlManagerCreateUrlTest.php
Labels: status:code review, type:bug

#18615 Fix #18611: Add note about isAcquired() behavior to Mutex
  framework/mutex/Mutex.php
Labels: type:docs

#18569 Add property $allowArray to NumberValidator.php
  framework/CHANGELOG.md
  framework/validators/NumberValidator.php
  tests/framework/validators/NumberValidatorTest.php
Labels: status:ready for merge

#18620 Do not modify `yii\web\Cookie::$path`
  framework/CHANGELOG.md
  framework/web/Response.php
Labels: type:bug

#18622 Fix PHP8 deprecation
  tests/framework/di/ContainerTest.php
Labels: type:bug, type:test

#18617 Fix for issue #18604
  framework/CHANGELOG.md
  framework/db/ColumnSchemaBuilder.php
  framework/db/mssql/ColumnSchemaBuilder.php
  framework/db/mssql/QueryBuilder.php
  framework/db/mssql/Schema.php
  tests/framework/db/mssql/QueryBuilderTest.php
Labels: status:code review

#18626 Improve docs
  framework/web/Request.php
Labels: type:docs
