Repository yiisoft/yii2, pull requests merged in 2021-02, with the labels that each got.

#18505 Fixed ArrayHelper::get() for ArrayAccess objects with explicitly defined properties
  framework/CHANGELOG.md
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: type:bug

#18518 Add support for ngrok's X-Original-Host header
  framework/CHANGELOG.md
  framework/web/Request.php
Labels: type:enhancement

#18513 Fixex #18499 - Query::$indexBy is auto-inserted into Query::$select in Query::all()
  docs/guide/db-query-builder.md
  framework/CHANGELOG.md
  framework/db/ActiveQueryInterface.php
  framework/db/Query.php
  framework/db/QueryInterface.php
  framework/db/QueryTrait.php
  tests/framework/db/QueryTest.php
Labels: status:code review

#18460 Compare Validator: Support of compareValue being also a closure
  docs/guide/tutorial-core-validators.md
  framework/CHANGELOG.md
  framework/validators/CompareValidator.php
  tests/framework/validators/CompareValidatorTest.php
Labels: status:ready for merge, type:enhancement

#18508 Update Schema.php
  framework/CHANGELOG.md
  framework/db/pgsql/Schema.php
Labels: status:code review, type:bug

#18533 Assets non-relative path with timestamp
  framework/CHANGELOG.md
  framework/web/AssetBundle.php
  framework/web/AssetManager.php
  tests/framework/web/AssetBundleTest.php
Labels: type:bug
