Repository yiisoft/yii2, pull requests merged in 2021-07, with the labels that each got.

#18705 Fix #18648: Fix `yii\web\Request` to properly handle HTTP Basic Auth …
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/filters/auth/BasicAuthTest.php
  tests/framework/web/RequestTest.php
Labels: status:code review

#18737 fix SchemaTest::testColumnSchema() for MySql <5.7
  tests/framework/db/mysql/SchemaTest.php
Labels: type:test

#18712 Formatter updates
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
  tests/framework/i18n/FormatterDateTest.php
  tests/framework/i18n/FormatterNumberTest.php
  tests/framework/i18n/FormatterTest.php
Labels: type:enhancement, type:test

#18707 Only log the $_SERVER information under YII_DEBUG
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/base/ErrorHandler.php
Labels: type:enhancement

#18744 update forum link (start-looking-ahead.md)
  docs/guide-ar/start-looking-ahead.md
  docs/guide-es/start-looking-ahead.md
  docs/guide-fr/start-looking-ahead.md
  docs/guide-id/start-looking-ahead.md
  docs/guide-ja/start-looking-ahead.md
  docs/guide-pl/start-looking-ahead.md
  docs/guide-pt-BR/start-looking-ahead.md
  docs/guide-ru/start-looking-ahead.md
  docs/guide-uk/start-looking-ahead.md
  docs/guide-uz/start-looking-ahead.md
  docs/guide-vi/start-looking-ahead.md
  docs/guide-zh-CN/start-looking-ahead.md
  docs/guide/start-looking-ahead.md
Labels: type:docs

#18742 Updated asUrl method to not introduce BC break
  framework/CHANGELOG.md
  framework/helpers/BaseUrl.php
  framework/i18n/Formatter.php
  tests/framework/i18n/FormatterTest.php
Labels: type:enhancement

#18747 Fixed tipfeler and inconsistencies regarding file translation
  framework/messages/hr/yii.php
Labels: type:enhancement

#18741 don't convert int to string if db type of column is numeric
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/db/ColumnSchema.php
  framework/db/ColumnSchemaBuilder.php
  tests/data/mysql.sql
  tests/framework/db/mysql/QueryBuilderTest.php
  tests/framework/db/mysql/SchemaTest.php
Labels: status:code review, type:bug

#18751 update yii forum & chat link
  docs/guide-es/structure-extensions.md
  docs/guide-fr/structure-extensions.md
  docs/guide-ja/structure-extensions.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-ru/structure-extensions.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide/structure-extensions.md
  docs/internals-ja/report-an-issue.md
  docs/internals-pl/report-an-issue.md
  docs/internals-ru/report-an-issue.md
  docs/internals-sr-Latn/report-an-issue.md
  docs/internals-uk/report-an-issue.md
  docs/internals/report-an-issue.md
Labels: type:docs

#18754 Fix $value parameter types in Formatter::normalizeDatetimeValue()
  framework/i18n/Formatter.php
Labels: type:docs

#18760 update structure block
  docs/guide-es/structure-modules.md
  docs/guide-fr/structure-modules.md
  docs/guide-ja/structure-modules.md
  docs/guide-pt-BR/structure-modules.md
  docs/guide-ru/structure-modules.md
  docs/guide-vi/structure-modules.md
  docs/guide-zh-CN/structure-modules.md
  docs/guide/structure-modules.md
Labels: type:docs

#18764 update composer.json links
  composer.json
Labels: type:docs

#18774 update twig link
  docs/guide-es/structure-extensions.md
  docs/guide-es/structure-views.md
  docs/guide-es/tutorial-template-engines.md
  docs/guide-fr/structure-extensions.md
  docs/guide-fr/structure-views.md
  docs/guide-ja/structure-extensions.md
  docs/guide-ja/structure-views.md
  docs/guide-ja/tutorial-template-engines.md
  docs/guide-pl/tutorial-template-engines.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-pt-BR/structure-views.md
  docs/guide-ru/structure-extensions.md
  docs/guide-ru/structure-views.md
  docs/guide-ru/tutorial-template-engines.md
  docs/guide-uk/structure-views.md
  docs/guide-uk/tutorial-template-engines.md
  docs/guide-vi/structure-views.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide-zh-CN/structure-views.md
  docs/guide-zh-CN/tutorial-template-engines.md
  docs/guide/structure-extensions.md
  docs/guide/structure-views.md
  docs/guide/tutorial-template-engines.md
Labels: type:docs

#18780 update fontawesome link
  docs/guide-es/structure-assets.md
  docs/guide-fr/structure-assets.md
  docs/guide-ja/structure-assets.md
  docs/guide-pt-BR/structure-assets.md
  docs/guide-ru/structure-assets.md
  docs/guide-zh-CN/structure-assets.md
  docs/guide/structure-assets.md
Labels: type:docs

#18781 Make docs gender agnostics
  framework/web/User.php
Labels: type:docs

#18787 PL Guide updates
  docs/guide-pl/README.md
  docs/guide-pl/intro-upgrade-from-v1.md
  docs/guide-pl/intro-yii.md
  docs/guide-pl/start-installation.md
Labels: type:docs

#18788 Allows router to be aliased
  framework/CHANGELOG.md
  framework/console/controllers/ServeController.php
Labels: type:enhancement

#18753 Fix PhpDoc for yii\db\QueryInterface
  framework/db/QueryInterface.php
Labels: type:docs

#18790 update stylus link
  docs/guide-es/structure-assets.md
  docs/guide-fr/structure-assets.md
  docs/guide-ja/structure-assets.md
  docs/guide-pt-BR/structure-assets.md
  docs/guide-ru/structure-assets.md
  docs/guide-zh-CN/structure-assets.md
  docs/guide/structure-assets.md
Labels: type:docs

#18791 Fix profiling with short flush interval
  framework/CHANGELOG.md
  framework/log/Logger.php
  tests/framework/log/LoggerTest.php
  tests/framework/log/TargetTest.php
Labels: type:bug
