Repository yiisoft/yii2, pull requests merged in 2021-08, with the labels that each got.

#18797 update composer asset plugin link
  docs/guide-ar/start-installation.md
  docs/guide-es/start-installation.md
  docs/guide-es/structure-extensions.md
  docs/guide-es/tutorial-yii-integration.md
  docs/guide-fr/start-installation.md
  docs/guide-fr/structure-assets.md
  docs/guide-fr/structure-extensions.md
  docs/guide-id/start-installation.md
  docs/guide-it/start-installation.md
  docs/guide-ja/start-installation.md
  docs/guide-ja/structure-assets.md
  docs/guide-ja/structure-extensions.md
  docs/guide-pl/start-installation.md
  docs/guide-pt-BR/start-installation.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-pt-BR/tutorial-yii-integration.md
  docs/guide-ru/structure-assets.md
  docs/guide-ru/tutorial-yii-integration.md
  docs/guide-uk/start-installation.md
  docs/guide-uk/tutorial-yii-integration.md
  docs/guide-vi/start-installation.md
  docs/guide-zh-CN/start-installation.md
  docs/guide-zh-CN/structure-assets.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide/start-installation.md
  docs/guide/structure-assets.md
  docs/guide/structure-extensions.md
Labels: type:docs

#18802 Update URLs
  composer.json
  framework/composer.json
Labels: status:code review

#18805 fix core framework code style link
  docs/guide-es/structure-extensions.md
  docs/guide-fr/structure-extensions.md
  docs/guide-ja/structure-extensions.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-ru/structure-extensions.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide/structure-extensions.md
Labels: type:docs

#18757 Fix \yii\validators\ExistValidator::queryValueExists non unique array
  framework/CHANGELOG.md
  framework/validators/ExistValidator.php
  tests/framework/validators/ExistValidatorTest.php
Labels: type:bug

#18809 Japanese document updated
  docs/guide-ja/db-active-record.md
  docs/guide-ja/db-migrations.md
  docs/guide-ja/db-query-builder.md
  docs/guide-ja/helper-json.md
  docs/guide-ja/helper-overview.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/security-authentication.md
  docs/guide-ja/security-best-practices.md
  docs/guide-ja/security-passwords.md
  docs/guide-ja/structure-models.md
  docs/guide-ja/test-environment-setup.md
  docs/guide-ja/tutorial-core-validators.md
Labels: type:docs

#18806 Optimize `yii\validators\ExistValidator`
  framework/validators/ExistValidator.php
Labels: type:enhancement

#18683 Document that link() will not trigger events/behaviors
  framework/db/BaseActiveRecord.php
Labels: type:docs, status:to be verified

#18800 Preventing breaking profiling messages when flushing
  framework/CHANGELOG.md
  framework/log/Logger.php
  tests/framework/log/LoggerTest.php
  tests/framework/log/TargetTest.php
Labels: type:enhancement

#18807 BUGFIX `yii\helpers\BaseStringHelper::mb_ucwords`
  framework/CHANGELOG.md
  framework/helpers/BaseStringHelper.php
  tests/framework/helpers/StringHelperTest.php
Labels: type:bug, status:code review

#18816 update Elasticsearch link
  docs/guide-es/structure-extensions.md
  docs/guide-fr/structure-extensions.md
  docs/guide-ja/structure-extensions.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-ru/structure-extensions.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide/structure-extensions.md
Labels: type:docs

#18817 Use `paragonie/random_compat` for random bytes generation, add CSPRNG-based `Security::generateRandomInt()` and use it everywhere
  composer.json
  composer.lock
  framework/CHANGELOG.md
  framework/base/Security.php
  framework/caching/DbCache.php
  framework/caching/FileCache.php
  framework/captcha/CaptchaAction.php
  framework/composer.json
  framework/mail/BaseMailer.php
  tests/framework/base/SecurityTest.php
  tests/framework/validators/FileValidatorTest.php
  tests/framework/web/UploadedFileTest.php
Labels: severity:security

#18680 Added user-friendly error messages for NumberFormatter configuration
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
  tests/framework/i18n/FormatterNumberTest.php
Labels: type:enhancement, status:ready for merge

#18824 update mongodb link
  docs/guide-es/runtime-sessions-cookies.md
  docs/guide-es/structure-extensions.md
  docs/guide-fr/runtime-sessions-cookies.md
  docs/guide-fr/structure-extensions.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-ja/structure-extensions.md
  docs/guide-pt-BR/runtime-sessions-cookies.md
  docs/guide-pt-BR/structure-extensions.md
  docs/guide-ru/runtime-sessions-cookies.md
  docs/guide-ru/structure-extensions.md
  docs/guide-zh-CN/runtime-sessions-cookies.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide/runtime-sessions-cookies.md
  docs/guide/structure-extensions.md
Labels: type:docs

#18649 Issue #18646 Cleanup auth data from session if findIdentity() returns…
  framework/CHANGELOG.md
  framework/web/User.php
  tests/framework/filters/auth/BasicAuthTest.php
Labels: type:bug, status:ready for merge

#18826 Add ability to turn the sorting off for a clicked column in GridView with multisort
  framework/CHANGELOG.md
  framework/data/Sort.php
  tests/framework/data/SortTest.php
Labels: type:enhancement

#18833 Fix #18832 - Inflector::camel2words() adding extra spaces
  framework/CHANGELOG.md
  framework/helpers/BaseInflector.php
  tests/framework/helpers/InflectorTest.php
Labels: type:bug

#18834 Added missing note for $categoryMap
  framework/UPGRADE.md
Labels: type:docs

#18835 fix invalid link & update
  docs/guide-fr/runtime-bootstrapping.md
  docs/guide-ja/runtime-bootstrapping.md
  docs/guide-pl/runtime-bootstrapping.md
  docs/guide-pt-BR/runtime-bootstrapping.md
  docs/guide-ru/runtime-bootstrapping.md
  docs/guide-zh-CN/runtime-bootstrapping.md
  docs/guide/runtime-bootstrapping.md
Labels: type:docs

#18823 Rollback #18806 in `ExistValidator::checkTargetRelationExistence()`
  framework/CHANGELOG.md
  framework/validators/ExistValidator.php
Labels: type:bug

#18839 docs: update RFC 7239 link
  docs/guide-ja/runtime-requests.md
  docs/guide/runtime-requests.md
  framework/web/Request.php
Labels: type:docs

#18841 Global setLogger was added in Dispatcher, if Logger was configured in…
  framework/CHANGELOG.md
  framework/log/Dispatcher.php
  tests/framework/log/DispatcherTest.php
Labels: status:code review

#18848 update Nginx: X-Accel-Redirec link
  docs/guide-es/runtime-responses.md
  docs/guide-fr/runtime-responses.md
  docs/guide-ja/runtime-responses.md
  docs/guide-ru/runtime-responses.md
  docs/guide-zh-CN/runtime-responses.md
  docs/guide/runtime-responses.md
Labels: type:docs

#18851 update HttpOnly wiki article link
  docs/guide-es/runtime-sessions-cookies.md
  docs/guide-fr/runtime-sessions-cookies.md
  docs/guide-ja/runtime-sessions-cookies.md
  docs/guide-pt-BR/runtime-sessions-cookies.md
  docs/guide-ru/runtime-sessions-cookies.md
  docs/guide-zh-CN/runtime-sessions-cookies.md
  docs/guide/runtime-sessions-cookies.md
Labels: type:docs

#18783 BUGFIX: `XmlResponseFormatter` element names with namespace
  framework/CHANGELOG.md
  framework/web/XmlResponseFormatter.php
  tests/framework/web/XmlResponseFormatterTest.php
Labels: status:code review

#18762 Json processdata fix for objects with zero-indexed keys
  framework/CHANGELOG.md
  framework/UPGRADE.md
  framework/helpers/BaseJson.php
  framework/web/JsonResponseFormatter.php
  tests/framework/helpers/JsonTest.php
  tests/framework/web/JsonResponseFormatterTest.php
Labels: type:enhancement

#18860 add optimisticLock to other lang
  docs/guide-fr/db-active-record.md
  docs/guide-ja/db-active-record.md
  docs/guide-zh-CN/db-active-record.md
Labels: type:docs
