Repository yiisoft/yii2, pull requests merged in 2022-06, with the labels that each got.

#19422 Fix outdated links in Formatter
  framework/i18n/Formatter.php
Labels: type:docs

#19419 Normalize PhpDoc types in AssetsManager
  framework/web/AssetManager.php
Labels: type:docs

#19402 Update `\yii\base\ErrorHandler`
  framework/CHANGELOG.md
  framework/base/ErrorHandler.php
Labels: type:enhancement

#19403 Small fixes in `yii\web\SessionIterator`
  framework/CHANGELOG.md
  framework/web/SessionIterator.php
Labels: type:bug

#19401 Delay exit in error handler
  framework/CHANGELOG.md
  framework/base/ErrorHandler.php
Labels: type:enhancement

#19424 Make docs more clear about the length of the result
  framework/helpers/BaseStringHelper.php
Labels: type:docs

#19425 Truncate help add method and suffix
  framework/helpers/BaseStringHelper.php
Labels: type:docs

#19428 update memcached link
  docs/guide/caching-data.md
Labels: type:docs

#19427 Update intro-yii.md & intro-upgrade-from-v1.md & add start-prerequisites.md translation [id]
  docs/guide-id/intro-upgrade-from-v1.md
  docs/guide-id/intro-yii.md
  docs/guide-id/start-prerequisites.md
Labels: type:docs

#19433 update bower link
  docs/guide-ja/concept-aliases.md
  docs/guide-ja/start-installation.md
  docs/guide-pt-BR/concept-aliases.md
  docs/guide-zh-CN/concept-aliases.md
  docs/guide-zh-CN/start-installation.md
  docs/guide-zh-CN/structure-assets.md
  docs/guide/structure-assets.md
  docs/guide/structure-extensions.md
Labels: type:docs

#19435 Update start-installation.md
  docs/guide-ja/start-installation.md
Labels: type:docs

#19436 Fix manual cubrid links
  framework/db/cubrid/QueryBuilder.php
  framework/db/cubrid/Schema.php
Labels: type:docs

#19319 fix: typecast for backed enums
  framework/CHANGELOG.md
  framework/db/ColumnSchema.php
Labels: php8

#19418 fix composite auth ignore only/except filters of auth methods
  framework/CHANGELOG.md
  framework/filters/auth/CompositeAuth.php
  tests/framework/filters/auth/CompositeAuthTest.php
Labels: type:bug

#19441 update sitepoint link
  docs/guide/output-data-widgets.md
Labels: type:docs

#19437 Support for 'X-Forwarded-Port' header in `\yii\web\Request`
  docs/guide/runtime-requests.md
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: type:enhancement

#19431 Improve reflection param/return types in console\Controller
  framework/console/Controller.php
Labels: status:code review

#19443 Fix null url in redirect
  framework/CHANGELOG.md
  framework/web/Response.php
  tests/framework/web/ResponseTest.php
Labels: type:bug, php8

#19452 update HATEOAS link
  docs/guide-ja/rest-quick-start.md
  docs/guide-ru/rest-quick-start.md
  docs/guide-uk/rest-quick-start.md
  docs/guide-zh-CN/rest-quick-start.md
Labels: type:docs

#19453 Update ActiveRelationTrait.php
  framework/db/ActiveRelationTrait.php
Labels: type:docs

#19460 Replace '```js' with '```' due some display problems
  docs/guide-es/start-workflow.md
  docs/guide-es/structure-modules.md
  docs/guide-fr/start-workflow.md
  docs/guide-fr/structure-modules.md
  docs/guide-id/start-workflow.md
  docs/guide-ja/start-workflow.md
  docs/guide-ja/structure-modules.md
  docs/guide-pl/start-workflow.md
  docs/guide-pt-BR/start-workflow.md
  docs/guide-pt-BR/structure-modules.md
  docs/guide-ru/start-workflow.md
  docs/guide-ru/structure-modules.md
  docs/guide-uk/start-workflow.md
  docs/guide-uz/start-workflow.md
  docs/guide-vi/start-workflow.md
  docs/guide-vi/structure-modules.md
  docs/guide-zh-CN/start-workflow.md
  docs/guide-zh-CN/structure-modules.md
Labels: type:docs

#19461 update cherokee-project link
  docs/guide/runtime-responses.md
Labels: type:docs
