Repository yiisoft/yii2, pull requests merged in 2022-04, with the labels that each got.

#19337 Fix autoload in composer.json
  composer.json
Labels: status:code review

#19328 Fix OCI trim error
  framework/CHANGELOG.md
  framework/db/oci/Schema.php
Labels: type:bug

#19278 Extend examples in `guide/input-tabular-input.md`
  docs/guide/input-tabular-input.md
Labels: type:docs

#19296 add alias text/rtf for rtf files (#19295)
  build/controllers/MimeTypeController.php
  framework/CHANGELOG.md
  framework/helpers/mimeAliases.php
  tests/framework/helpers/MimeTest.php
Labels: type:enhancement

#19336 Resolve #19327
  framework/CHANGELOG.md
  framework/db/oci/Schema.php
Labels: type:bug, php8

#19341 Improve DataFilterTest
  tests/framework/data/DataFilterTest.php
Labels: type:test

#19312 Early result at passing empty values to BaseInflector methods
  framework/CHANGELOG.md
  framework/helpers/BaseInflector.php
Labels: type:bug, php8

#19348 Allow null values for date formatters in `yii\i18n\Formatter`
  framework/i18n/Formatter.php
Labels: type:docs

#19353 Fix generation of docs on the site
  framework/base/ErrorHandler.php
Labels: type:bug

#19301 fix Request::getHostInfo() doesn’t return the port if a Host header is used (#19290)
  framework/CHANGELOG.md
  framework/web/Request.php
  tests/framework/web/RequestTest.php
Labels: type:bug, status:ready for merge

#19272 Fixed issue when trying to check if a multidimensional array is dirty…
  framework/CHANGELOG.md
  framework/db/BaseActiveRecord.php
  framework/helpers/BaseArrayHelper.php
  tests/framework/helpers/ArrayHelperTest.php
Labels: type:bug, status:code review

#19357 Add guide section for filtering REST collection.
  docs/guide/README.md
  docs/guide/rest-filtering-collections.md
  docs/guide/rest-quick-start.md
  docs/guide/rest-resources.md
  framework/rest/IndexAction.php
Labels: type:docs

#19363 Optimize BaseArrayHelper::isIndexed()
  framework/helpers/BaseArrayHelper.php
Labels: type:enhancement

#19364 add uk rest-quick-start.md
  docs/guide-uk/README.md
  docs/guide-uk/rest-quick-start.md
Labels: type:docs

#19369 Fix FileValidator for empty fileMimeType and PHP 8.1
  framework/CHANGELOG.md
  framework/validators/FileValidator.php
Labels: type:bug, php8
