Repository yiisoft/yii2, pull requests merged in 2022-03, with the labels that each got.

#19283 update links
  docs/guide-pt-BR/concept-di-container.md
  docs/guide-pt-BR/rest-authentication.md
  docs/guide-pt-BR/rest-quick-start.md
  docs/guide-pt-BR/rest-response-formatting.md
  docs/guide-pt-BR/start-looking-ahead.md
  docs/guide-pt-BR/structure-applications.md
  docs/guide-pt-BR/structure-filters.md
  docs/guide-pt-BR/structure-models.md
  docs/guide-pt-BR/structure-views.md
  docs/guide-pt-BR/tutorial-yii-integration.md
  docs/guide-ru/concept-di-container.md
  docs/guide-ru/input-validation.md
  docs/guide-ru/output-formatting.md
  docs/guide-ru/rest-authentication.md
  docs/guide-ru/structure-applications.md
  docs/guide-ru/structure-assets.md
  docs/guide-ru/structure-filters.md
  docs/guide-ru/structure-models.md
  docs/guide-ru/test-fixtures.md
  docs/guide-ru/tutorial-i18n.md
  docs/guide-ru/tutorial-yii-integration.md
Labels: type:docs

#19286 Fix @param type
  framework/helpers/BaseConsole.php
Labels: type:docs

#19288 update links (uk, uz lang)
  docs/guide-uk/concept-aliases.md
  docs/guide-uk/start-forms.md
  docs/guide-uk/start-hello.md
  docs/guide-uk/start-installation.md
  docs/guide-uk/start-looking-ahead.md
  docs/guide-uk/start-workflow.md
  docs/guide-uk/structure-applications.md
  docs/guide-uk/structure-controllers.md
  docs/guide-uk/structure-models.md
  docs/guide-uk/structure-overview.md
  docs/guide-uk/structure-views.md
  docs/guide-uk/tutorial-start-from-scratch.md
  docs/guide-uk/tutorial-yii-integration.md
  docs/guide-uz/start-hello.md
  docs/guide-uz/start-installation.md
  docs/guide-uz/start-workflow.md
Labels: type:docs

#19291 Fix `Model::__clone()`
  framework/CHANGELOG.md
  framework/base/Model.php
Labels: type:bug

#19294 update links (vi, zh lang)
  docs/guide-vi/intro-upgrade-from-v1.md
  docs/guide-vi/start-forms.md
  docs/guide-vi/start-hello.md
  docs/guide-vi/start-installation.md
  docs/guide-vi/start-looking-ahead.md
  docs/guide-vi/start-workflow.md
  docs/guide-vi/structure-controllers.md
  docs/guide-vi/structure-entry-scripts.md
  docs/guide-vi/structure-models.md
  docs/guide-vi/structure-overview.md
  docs/guide-vi/structure-views.md
  docs/guide-zh-CN/caching-data.md
  docs/guide-zh-CN/db-dao.md
  docs/guide-zh-CN/output-client-scripts.md
  docs/guide-zh-CN/output-data-widgets.md
  docs/guide-zh-CN/rest-resources.md
  docs/guide-zh-CN/runtime-responses.md
  docs/guide-zh-CN/runtime-sessions-cookies.md
  docs/guide-zh-CN/start-forms.md
  docs/guide-zh-CN/start-hello.md
  docs/guide-zh-CN/start-looking-ahead.md
  docs/guide-zh-CN/structure-extensions.md
  docs/guide-zh-CN/structure-overview.md
  docs/guide-zh-CN/structure-views.md
  docs/guide-zh-CN/test-acceptance.md
  docs/guide-zh-CN/tutorial-performance-tuning.md
  docs/guide-zh-CN/tutorial-start-from-scratch.md
  docs/guide-zh-CN/yii2-redis.md
Labels: type:docs

#19298 Update links (internals)
  docs/internals-es/translation-workflow.md
  docs/internals-ja/core-code-style.md
  docs/internals-ja/git-workflow.md
  docs/internals-ja/translation-workflow.md
  docs/internals-ja/versions.md
  docs/internals-pl/core-code-style.md
  docs/internals-pl/git-workflow.md
  docs/internals-pl/translation-workflow.md
  docs/internals-pt-BR/translation-workflow.md
  docs/internals-ru/core-code-style.md
  docs/internals-ru/git-workflow.md
  docs/internals-ru/translation-workflow.md
  docs/internals-sr-Latn/git-workflow.md
  docs/internals-sr-Latn/translation-workflow.md
  docs/internals-uk/core-code-style.md
  docs/internals-uk/git-workflow.md
  docs/internals-uk/translation-workflow.md
  docs/internals-uk/versions.md
  docs/internals/core-code-style.md
  docs/internals/git-workflow.md
  docs/internals/translation-workflow.md
  docs/internals/versions.md
Labels: type:docs

#19300 update internals links
  docs/internals-fa/core-code-style.md
  docs/internals-pl/versions.md
  docs/internals-ru/translation-workflow.md
  docs/internals-uz/translation-workflow.md
Labels: type:docs

#19309 Rewrite Model::attributes()
  framework/CHANGELOG.md
  framework/base/Model.php
Labels: type:enhancement

#19304 Add TrimValidator
  framework/CHANGELOG.md
  framework/validators/TrimValidator.php
  framework/validators/Validator.php
Labels: type:enhancement

#19323 Reverse force setting value to empty string
  framework/CHANGELOG.md
  framework/validators/FilterValidator.php
  tests/framework/base/ModelTest.php
Labels: type:bug

#19303 Fix yii\caching\Dependency::generateReusableHash()
  framework/CHANGELOG.md
  framework/caching/Dependency.php
  tests/framework/caching/DbQueryDependencyTest.php
Labels: type:bug

#19330 GroupUrlRule slash in prefix
  framework/CHANGELOG.md
  framework/web/GroupUrlRule.php
  tests/framework/web/GroupUrlRuleTest.php
Labels: type:bug

#19308 Add `yii\web\UploadedFile::$fullPath`
  framework/CHANGELOG.md
  framework/web/UploadedFile.php
Labels: type:enhancement

#19254 Replace deprecated $.trim() in yii.validation.js
  framework/CHANGELOG.md
  framework/assets/yii.validation.js
Labels: type:enhancement, JS
