Repository yiisoft/yii2, pull requests merged in 2023-10, with the labels that each got.

#19984 Do not duplicate log messages
  framework/CHANGELOG.md
  framework/log/FileTarget.php
Labels: type:enhancement

#20006 Fixed a bug with the yii serve command and a custom router
  framework/console/controllers/ServeController.php
Labels: type:enhancement

#19934 Fix #19927: Refactor DB message saving mechanism
  framework/CHANGELOG.md
  framework/console/controllers/MessageController.php
Labels: status:code review

#20009 Fix `MaskedInputAsset::class`.
  composer.json
  framework/composer.json
  framework/widgets/MaskedInputAsset.php
Labels: type:enhancement

#19909 Fix #13920: Fixed erroneous validation for specific cases
  framework/CHANGELOG.md
  framework/assets/yii.activeForm.js
  tests/js/data/yii.activeForm.html
  tests/js/tests/yii.activeForm.test.js
Labels: pr:request for unit tests

#19995 Added 'zh' into 'framework/messages/config.php'
  framework/messages/config.php
Labels: status:need more info

#20007 fix: #20002 optimize head request on serializeDataProvider
  framework/CHANGELOG.md
  framework/rest/Serializer.php
  tests/framework/rest/SerializerTest.php
Labels: type:enhancement

#19061 Menu widget active with Closure #19060
  framework/CHANGELOG.md
  framework/widgets/Menu.php
  tests/framework/widgets/MenuTest.php
Labels: type:bug

#20033 Improve performance of handling `ErrorHandler::$memoryReserveSize`
  framework/CHANGELOG.md
  framework/base/ErrorHandler.php
Labels: type:enhancement

#20032 Implement StringHelper::mask Method
  framework/CHANGELOG.md
  framework/helpers/BaseStringHelper.php
  tests/framework/helpers/StringHelperTest.php
Labels: type:enhancement

#20043 Add empty array check to `ActiveQueryTrait::findWith()`
  framework/CHANGELOG.md
  framework/db/ActiveQueryTrait.php
Labels: type:enhancement

#20046 Add test for boolean type `SQLite`.
  tests/framework/db/sqlite/type/BooleanTest.php
Labels: type:test

#20054 Refine Persian Coding Standards Documentation in core-code-style File
  docs/internals-fa/core-code-style.md
Labels: type:docs

#20052 Add tests for uncovered lines in DbDependency
  tests/framework/caching/DbDependencyTest.php
Labels: type:test

#20051 Add Missing Tests for convertExceptionToString and convertExceptionToArray methods
  tests/framework/web/ErrorHandlerTest.php
Labels: type:test

#20049 Add test for boolean type `PostgreSQL`.
  tests/framework/db/pgsql/type/BooleanTest.php
Labels: type:test

#20034 Implement StringHelper::findBetween Method
  framework/CHANGELOG.md
  framework/helpers/BaseStringHelper.php
  tests/framework/helpers/StringHelperTest.php
Labels: type:enhancement
