Repository yiisoft/yii2, pull requests merged in 2023-05, with the labels that each got.

#19816 Explicity pass $fallbackToMaster to getSlavePdo()
  framework/CHANGELOG.md
  framework/db/Command.php
  framework/db/Connection.php
  framework/db/Schema.php
  framework/db/cubrid/Schema.php
  framework/db/mysql/QueryBuilder.php
  framework/db/mysql/Schema.php
  tests/framework/db/ConnectionTest.php
  tests/framework/db/SchemaTest.php
  tests/framework/db/cubrid/QueryBuilderTest.php
  tests/framework/db/mysql/QueryBuilderTest.php
Labels: type:enhancement

#19813 Fix validation on missing attributes in DynamicModel
  framework/CHANGELOG.md
  framework/base/DynamicModel.php
  tests/framework/base/DynamicModelTest.php
Labels: type:enhancement

#19830 Update `LikeCondition::setEscapingReplacements()` phpdoc
  framework/db/conditions/LikeCondition.php
Labels: type:docs

#19837 Mime type fixes
  build/controllers/MimeTypeController.php
  framework/CHANGELOG.md
  framework/helpers/mimeTypes.php
  tests/framework/helpers/MimeTest.php
Labels: type:bug

#19838 Filehelper::getExtensionByMimeType()
  build/controllers/MimeTypeController.php
  framework/CHANGELOG.md
  framework/helpers/BaseFileHelper.php
  framework/helpers/mimeExtensions.php
  framework/helpers/mimeTypes.php
  tests/framework/helpers/FileHelperTest.php
  tests/framework/helpers/MimeTest.php
Labels: type:enhancement

#19807 Update Serializer.php
  framework/CHANGELOG.md
  framework/rest/Serializer.php
Labels: type:enhancement

#19749 PHP 8.2 support
  .github/workflows/build.yml
  composer.lock
  framework/CHANGELOG.md
  framework/composer.json
  framework/db/Schema.php
  framework/db/conditions/LikeConditionBuilder.php
  tests/framework/caching/MemCacheTest.php
  tests/framework/caching/MemCachedTest.php
  tests/framework/widgets/LinkSorterTest.php
Labels: type:bug, needs funding

#19846 Update structure-models.md
  docs/guide/structure-models.md
Labels: type:docs

#19848 Bugfix: Clear rbac cache when assigning or revoking roles from a user
  framework/CHANGELOG.md
  framework/rbac/DbManager.php
  tests/framework/rbac/DbManagerTestCase.php
Labels: type:bug
