Repository yiisoft/yii2, pull requests merged in 2025-09, with the labels that each got.

#20542 Handles situations with more complex ICU unit data structure
  framework/CHANGELOG.md
  framework/i18n/Formatter.php
Labels: type:bug

#20550 Add the `convertIniSizeToBytes` method to `BaseStringHelper`
  framework/CHANGELOG.md
  framework/helpers/BaseStringHelper.php
  framework/validators/FileValidator.php
  tests/framework/helpers/StringHelperTest.php
  tests/framework/validators/FileValidatorTest.php
Labels: type:feature

#20552 Add code coverage `100%` to `ActiveForm::class`.
  package.json
  tests/framework/widgets/ActiveFormTest.php
Labels: type:test, 22
